// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msg/auth.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//账号验证
type Auth_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToServerId int32  `protobuf:"varint,1,opt,name=toServerId,proto3" json:"toServerId,omitempty"` //如果==0 进入默认服务器
	AccountId  string `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
}

func (x *Auth_C) Reset() {
	*x = Auth_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_C) ProtoMessage() {}

func (x *Auth_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_C.ProtoReflect.Descriptor instead.
func (*Auth_C) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{0}
}

func (x *Auth_C) GetToServerId() int32 {
	if x != nil {
		return x.ToServerId
	}
	return 0
}

func (x *Auth_C) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type Auth_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Token  string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Auth_S) Reset() {
	*x = Auth_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth_S) ProtoMessage() {}

func (x *Auth_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth_S.ProtoReflect.Descriptor instead.
func (*Auth_S) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Auth_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Auth_S) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Platform      string `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` //android ios
	Deviceid      string `protobuf:"bytes,2,opt,name=deviceid,proto3" json:"deviceid,omitempty"`
	Clientversion string `protobuf:"bytes,3,opt,name=clientversion,proto3" json:"clientversion,omitempty"` //1.2.3
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ClientInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *ClientInfo) GetDeviceid() string {
	if x != nil {
		return x.Deviceid
	}
	return ""
}

func (x *ClientInfo) GetClientversion() string {
	if x != nil {
		return x.Clientversion
	}
	return ""
}

type Login_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientInfo *ClientInfo `protobuf:"bytes,1,opt,name=clientInfo,proto3" json:"clientInfo,omitempty"` //客户端设备信息
}

func (x *Login_C) Reset() {
	*x = Login_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_C) ProtoMessage() {}

func (x *Login_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_C.ProtoReflect.Descriptor instead.
func (*Login_C) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{3}
}

func (x *Login_C) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

type Login_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result         int32  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ServerTime     int64  `protobuf:"varint,2,opt,name=serverTime,proto3" json:"serverTime,omitempty"`         //服务器当前时间
	ServerOpenTime int64  `protobuf:"varint,3,opt,name=serverOpenTime,proto3" json:"serverOpenTime,omitempty"` //服务器开启时间
	TimeZone       string `protobuf:"bytes,4,opt,name=timeZone,proto3" json:"timeZone,omitempty"`              //时区
}

func (x *Login_S) Reset() {
	*x = Login_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login_S) ProtoMessage() {}

func (x *Login_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login_S.ProtoReflect.Descriptor instead.
func (*Login_S) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{4}
}

func (x *Login_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *Login_S) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *Login_S) GetServerOpenTime() int64 {
	if x != nil {
		return x.ServerOpenTime
	}
	return 0
}

func (x *Login_S) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

//玩家基本信息 PLAYERINFO_S
type PlayerInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result        int32  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	PlayerId      string `protobuf:"bytes,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon          int32  `protobuf:"varint,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Level         int32  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int32  `protobuf:"varint,6,opt,name=exp,proto3" json:"exp,omitempty"`
	LastLoginTime int64  `protobuf:"varint,7,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
}

func (x *PlayerInfo_S) Reset() {
	*x = PlayerInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo_S) ProtoMessage() {}

func (x *PlayerInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo_S.ProtoReflect.Descriptor instead.
func (*PlayerInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PlayerInfo_S) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInfo_S) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo_S) GetIcon() int32 {
	if x != nil {
		return x.Icon
	}
	return 0
}

func (x *PlayerInfo_S) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerInfo_S) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *PlayerInfo_S) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

//跨天
type CrossDay_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CrossDay_C) Reset() {
	*x = CrossDay_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossDay_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossDay_C) ProtoMessage() {}

func (x *CrossDay_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossDay_C.ProtoReflect.Descriptor instead.
func (*CrossDay_C) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{6}
}

type CrossDay_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *CrossDay_S) Reset() {
	*x = CrossDay_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CrossDay_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrossDay_S) ProtoMessage() {}

func (x *CrossDay_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrossDay_S.ProtoReflect.Descriptor instead.
func (*CrossDay_S) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CrossDay_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type OpenFuncChange_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result    int32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	OpenFuncs []int32 `protobuf:"varint,2,rep,packed,name=openFuncs,proto3" json:"openFuncs,omitempty"` //开放的功能id，增量
}

func (x *OpenFuncChange_S) Reset() {
	*x = OpenFuncChange_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_auth_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenFuncChange_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenFuncChange_S) ProtoMessage() {}

func (x *OpenFuncChange_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_auth_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenFuncChange_S.ProtoReflect.Descriptor instead.
func (*OpenFuncChange_S) Descriptor() ([]byte, []int) {
	return file_msg_auth_proto_rawDescGZIP(), []int{8}
}

func (x *OpenFuncChange_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *OpenFuncChange_S) GetOpenFuncs() []int32 {
	if x != nil {
		return x.OpenFuncs
	}
	return nil
}

var File_msg_auth_proto protoreflect.FileDescriptor

var file_msg_auth_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x46, 0x0a, 0x06, 0x41, 0x75, 0x74, 0x68, 0x5f, 0x43, 0x12,
	0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x36, 0x0a,
	0x06, 0x41, 0x75, 0x74, 0x68, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x6a, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x22, 0x3a, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x43, 0x12, 0x2f, 0x0a, 0x0a,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x85, 0x01,
	0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4f, 0x70, 0x65, 0x6e, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x4f, 0x70, 0x65, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x6d,
	0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x6d,
	0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x22, 0xb8, 0x01, 0x0a, 0x0c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x69, 0x63,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x24, 0x0a, 0x0d, 0x6c, 0x61,
	0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x0c, 0x0a, 0x0a, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x44, 0x61, 0x79, 0x5f, 0x43, 0x22, 0x24,
	0x0a, 0x0a, 0x43, 0x72, 0x6f, 0x73, 0x73, 0x44, 0x61, 0x79, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x48, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x6e, 0x46, 0x75, 0x6e, 0x63,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x6e, 0x46, 0x75, 0x6e, 0x63, 0x73, 0x42, 0x0a,
	0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_msg_auth_proto_rawDescOnce sync.Once
	file_msg_auth_proto_rawDescData = file_msg_auth_proto_rawDesc
)

func file_msg_auth_proto_rawDescGZIP() []byte {
	file_msg_auth_proto_rawDescOnce.Do(func() {
		file_msg_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_auth_proto_rawDescData)
	})
	return file_msg_auth_proto_rawDescData
}

var file_msg_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_msg_auth_proto_goTypes = []interface{}{
	(*Auth_C)(nil),           // 0: msg.Auth_C
	(*Auth_S)(nil),           // 1: msg.Auth_S
	(*ClientInfo)(nil),       // 2: msg.ClientInfo
	(*Login_C)(nil),          // 3: msg.Login_C
	(*Login_S)(nil),          // 4: msg.Login_S
	(*PlayerInfo_S)(nil),     // 5: msg.PlayerInfo_S
	(*CrossDay_C)(nil),       // 6: msg.CrossDay_C
	(*CrossDay_S)(nil),       // 7: msg.CrossDay_S
	(*OpenFuncChange_S)(nil), // 8: msg.OpenFuncChange_S
}
var file_msg_auth_proto_depIdxs = []int32{
	2, // 0: msg.Login_C.clientInfo:type_name -> msg.ClientInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_msg_auth_proto_init() }
func file_msg_auth_proto_init() {
	if File_msg_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossDay_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CrossDay_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_auth_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenFuncChange_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_auth_proto_goTypes,
		DependencyIndexes: file_msg_auth_proto_depIdxs,
		MessageInfos:      file_msg_auth_proto_msgTypes,
	}.Build()
	File_msg_auth_proto = out.File
	file_msg_auth_proto_rawDesc = nil
	file_msg_auth_proto_goTypes = nil
	file_msg_auth_proto_depIdxs = nil
}
