// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msg/bag.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemChangeOp int32

const (
	ItemChangeOp_ITEM_UPDATE ItemChangeOp = 0 //数量更新
	ItemChangeOp_ITEM_ADD    ItemChangeOp = 1 //数量增加
	ItemChangeOp_ITEM_DEL    ItemChangeOp = 2 //数量减少
)

// Enum value maps for ItemChangeOp.
var (
	ItemChangeOp_name = map[int32]string{
		0: "ITEM_UPDATE",
		1: "ITEM_ADD",
		2: "ITEM_DEL",
	}
	ItemChangeOp_value = map[string]int32{
		"ITEM_UPDATE": 0,
		"ITEM_ADD":    1,
		"ITEM_DEL":    2,
	}
)

func (x ItemChangeOp) Enum() *ItemChangeOp {
	p := new(ItemChangeOp)
	*p = x
	return p
}

func (x ItemChangeOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItemChangeOp) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_bag_proto_enumTypes[0].Descriptor()
}

func (ItemChangeOp) Type() protoreflect.EnumType {
	return &file_msg_bag_proto_enumTypes[0]
}

func (x ItemChangeOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItemChangeOp.Descriptor instead.
func (ItemChangeOp) EnumDescriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{0}
}

//BAGINFO_S
type BagInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Bags   *ItemBag `protobuf:"bytes,2,opt,name=bags,proto3" json:"bags,omitempty"`
}

func (x *BagInfo_S) Reset() {
	*x = BagInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagInfo_S) ProtoMessage() {}

func (x *BagInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagInfo_S.ProtoReflect.Descriptor instead.
func (*BagInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{0}
}

func (x *BagInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *BagInfo_S) GetBags() *ItemBag {
	if x != nil {
		return x.Bags
	}
	return nil
}

//背包
type ItemBag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items    []*ItemInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`        //道具列表
	BagLevel int32       `protobuf:"varint,2,opt,name=bagLevel,proto3" json:"bagLevel,omitempty"` //背包等级
}

func (x *ItemBag) Reset() {
	*x = ItemBag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemBag) ProtoMessage() {}

func (x *ItemBag) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemBag.ProtoReflect.Descriptor instead.
func (*ItemBag) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{1}
}

func (x *ItemBag) GetItems() []*ItemInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ItemBag) GetBagLevel() int32 {
	if x != nil {
		return x.BagLevel
	}
	return 0
}

type ItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int32 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"` //道具ID
	Num    int64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`       //数量
	Sid    int32 `protobuf:"varint,3,opt,name=sid,proto3" json:"sid,omitempty"`       //唯一id
}

func (x *ItemInfo) Reset() {
	*x = ItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemInfo) ProtoMessage() {}

func (x *ItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemInfo.ProtoReflect.Descriptor instead.
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{2}
}

func (x *ItemInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemInfo) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ItemInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

//道具数量更新 BAGITEMUPDATE_S
type BagItemUpdate_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32             `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Infos  []*ItemChangeInfo `protobuf:"bytes,2,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *BagItemUpdate_S) Reset() {
	*x = BagItemUpdate_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagItemUpdate_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItemUpdate_S) ProtoMessage() {}

func (x *BagItemUpdate_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItemUpdate_S.ProtoReflect.Descriptor instead.
func (*BagItemUpdate_S) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{3}
}

func (x *BagItemUpdate_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *BagItemUpdate_S) GetInfos() []*ItemChangeInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

//道具变化信息
type ItemChangeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   ItemChangeOp `protobuf:"varint,1,opt,name=type,proto3,enum=msg.ItemChangeOp" json:"type,omitempty"`
	Sid    int32        `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	ItemId int32        `protobuf:"varint,3,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Num    int64        `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *ItemChangeInfo) Reset() {
	*x = ItemChangeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemChangeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemChangeInfo) ProtoMessage() {}

func (x *ItemChangeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemChangeInfo.ProtoReflect.Descriptor instead.
func (*ItemChangeInfo) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{4}
}

func (x *ItemChangeInfo) GetType() ItemChangeOp {
	if x != nil {
		return x.Type
	}
	return ItemChangeOp_ITEM_UPDATE
}

func (x *ItemChangeInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ItemChangeInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemChangeInfo) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

//背包升级 BAGLEVELUP_C
type BagLevelUp_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BagLevelUp_C) Reset() {
	*x = BagLevelUp_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagLevelUp_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagLevelUp_C) ProtoMessage() {}

func (x *BagLevelUp_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagLevelUp_C.ProtoReflect.Descriptor instead.
func (*BagLevelUp_C) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{5}
}

type BagLevelUp_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	NewLv  int32 `protobuf:"varint,2,opt,name=newLv,proto3" json:"newLv,omitempty"` //升级后的等级
}

func (x *BagLevelUp_S) Reset() {
	*x = BagLevelUp_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagLevelUp_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagLevelUp_S) ProtoMessage() {}

func (x *BagLevelUp_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagLevelUp_S.ProtoReflect.Descriptor instead.
func (*BagLevelUp_S) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{6}
}

func (x *BagLevelUp_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *BagLevelUp_S) GetNewLv() int32 {
	if x != nil {
		return x.NewLv
	}
	return 0
}

//背包升级 BAGLEVELUP_C
type BagSellItem_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SItems map[int32]int32 `protobuf:"bytes,1,rep,name=sItems,proto3" json:"sItems,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //<itemId, num>
}

func (x *BagSellItem_C) Reset() {
	*x = BagSellItem_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagSellItem_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagSellItem_C) ProtoMessage() {}

func (x *BagSellItem_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagSellItem_C.ProtoReflect.Descriptor instead.
func (*BagSellItem_C) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{7}
}

func (x *BagSellItem_C) GetSItems() map[int32]int32 {
	if x != nil {
		return x.SItems
	}
	return nil
}

//需要先删除再增加，所以道具变化使用 BagItemUpdate_S 消息通知
type BagSellItem_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *BagSellItem_S) Reset() {
	*x = BagSellItem_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BagSellItem_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagSellItem_S) ProtoMessage() {}

func (x *BagSellItem_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagSellItem_S.ProtoReflect.Descriptor instead.
func (*BagSellItem_S) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{8}
}

func (x *BagSellItem_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

//购买item
type BuyItems_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items map[int32]int32 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //itemId, num
}

func (x *BuyItems_C) Reset() {
	*x = BuyItems_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyItems_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItems_C) ProtoMessage() {}

func (x *BuyItems_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItems_C.ProtoReflect.Descriptor instead.
func (*BuyItems_C) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{9}
}

func (x *BuyItems_C) GetItems() map[int32]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

type BuyItems_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *BuyItems_S) Reset() {
	*x = BuyItems_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_bag_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyItems_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyItems_S) ProtoMessage() {}

func (x *BuyItems_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_bag_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyItems_S.ProtoReflect.Descriptor instead.
func (*BuyItems_S) Descriptor() ([]byte, []int) {
	return file_msg_bag_proto_rawDescGZIP(), []int{10}
}

func (x *BuyItems_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_msg_bag_proto protoreflect.FileDescriptor

var file_msg_bag_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x73, 0x67, 0x2f, 0x62, 0x61, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x45, 0x0a, 0x09, 0x42, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x5f,
	0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x62, 0x61, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x42, 0x61, 0x67, 0x52, 0x04, 0x62, 0x61, 0x67, 0x73, 0x22, 0x4a, 0x0a, 0x07, 0x49,
	0x74, 0x65, 0x6d, 0x42, 0x61, 0x67, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x62,
	0x61, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62,
	0x61, 0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x46, 0x0a, 0x08, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x10, 0x0a,
	0x03, 0x73, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x22,
	0x54, 0x0a, 0x0f, 0x42, 0x61, 0x67, 0x49, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x6e,
	0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x49, 0x74, 0x65, 0x6d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x73, 0x0a, 0x0e, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x0e, 0x0a, 0x0c, 0x42, 0x61,
	0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x5f, 0x43, 0x22, 0x3c, 0x0a, 0x0c, 0x42, 0x61,
	0x67, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x65, 0x77, 0x4c, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6e, 0x65, 0x77, 0x4c, 0x76, 0x22, 0x82, 0x01, 0x0a, 0x0d, 0x42, 0x61, 0x67,
	0x53, 0x65, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x43, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x42, 0x61, 0x67, 0x53, 0x65, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x43, 0x2e, 0x53,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x73, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x1a, 0x39, 0x0a, 0x0b, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x27, 0x0a,
	0x0d, 0x42, 0x61, 0x67, 0x53, 0x65, 0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x53, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x78, 0x0a, 0x0a, 0x42, 0x75, 0x79, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x5f, 0x43, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x42, 0x75, 0x79, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x5f, 0x43, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x24, 0x0a, 0x0a, 0x42, 0x75, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x53, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x3b, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x54, 0x45, 0x4d, 0x5f,
	0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x44, 0x45,
	0x4c, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_bag_proto_rawDescOnce sync.Once
	file_msg_bag_proto_rawDescData = file_msg_bag_proto_rawDesc
)

func file_msg_bag_proto_rawDescGZIP() []byte {
	file_msg_bag_proto_rawDescOnce.Do(func() {
		file_msg_bag_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_bag_proto_rawDescData)
	})
	return file_msg_bag_proto_rawDescData
}

var file_msg_bag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_bag_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_msg_bag_proto_goTypes = []interface{}{
	(ItemChangeOp)(0),       // 0: msg.ItemChangeOp
	(*BagInfo_S)(nil),       // 1: msg.BagInfo_S
	(*ItemBag)(nil),         // 2: msg.ItemBag
	(*ItemInfo)(nil),        // 3: msg.ItemInfo
	(*BagItemUpdate_S)(nil), // 4: msg.BagItemUpdate_S
	(*ItemChangeInfo)(nil),  // 5: msg.ItemChangeInfo
	(*BagLevelUp_C)(nil),    // 6: msg.BagLevelUp_C
	(*BagLevelUp_S)(nil),    // 7: msg.BagLevelUp_S
	(*BagSellItem_C)(nil),   // 8: msg.BagSellItem_C
	(*BagSellItem_S)(nil),   // 9: msg.BagSellItem_S
	(*BuyItems_C)(nil),      // 10: msg.BuyItems_C
	(*BuyItems_S)(nil),      // 11: msg.BuyItems_S
	nil,                     // 12: msg.BagSellItem_C.SItemsEntry
	nil,                     // 13: msg.BuyItems_C.ItemsEntry
}
var file_msg_bag_proto_depIdxs = []int32{
	2,  // 0: msg.BagInfo_S.bags:type_name -> msg.ItemBag
	3,  // 1: msg.ItemBag.items:type_name -> msg.ItemInfo
	5,  // 2: msg.BagItemUpdate_S.infos:type_name -> msg.ItemChangeInfo
	0,  // 3: msg.ItemChangeInfo.type:type_name -> msg.ItemChangeOp
	12, // 4: msg.BagSellItem_C.sItems:type_name -> msg.BagSellItem_C.SItemsEntry
	13, // 5: msg.BuyItems_C.items:type_name -> msg.BuyItems_C.ItemsEntry
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_msg_bag_proto_init() }
func file_msg_bag_proto_init() {
	if File_msg_bag_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_bag_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemBag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagItemUpdate_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemChangeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagLevelUp_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagLevelUp_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagSellItem_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BagSellItem_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyItems_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_bag_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyItems_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_bag_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_bag_proto_goTypes,
		DependencyIndexes: file_msg_bag_proto_depIdxs,
		EnumInfos:         file_msg_bag_proto_enumTypes,
		MessageInfos:      file_msg_bag_proto_msgTypes,
	}.Build()
	File_msg_bag_proto = out.File
	file_msg_bag_proto_rawDesc = nil
	file_msg_bag_proto_goTypes = nil
	file_msg_bag_proto_depIdxs = nil
}
