// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msg/elementshop.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//E_ElementShopInfo_C
type ElementShopInfo_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementShopInfo_C) Reset() {
	*x = ElementShopInfo_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementShopInfo_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementShopInfo_C) ProtoMessage() {}

func (x *ElementShopInfo_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementShopInfo_C.ProtoReflect.Descriptor instead.
func (*ElementShopInfo_C) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{0}
}

func (x *ElementShopInfo_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

//E_ElementShopInfo_S
type ElementShopInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result    int32                     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MapId     int32                     `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
	ShopModel *ElementShopBuildingModel `protobuf:"bytes,3,opt,name=shopModel,proto3" json:"shopModel,omitempty"`
	Handbooks []int32                   `protobuf:"varint,4,rep,packed,name=handbooks,proto3" json:"handbooks,omitempty"` //图鉴列表
}

func (x *ElementShopInfo_S) Reset() {
	*x = ElementShopInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementShopInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementShopInfo_S) ProtoMessage() {}

func (x *ElementShopInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementShopInfo_S.ProtoReflect.Descriptor instead.
func (*ElementShopInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{1}
}

func (x *ElementShopInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementShopInfo_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementShopInfo_S) GetShopModel() *ElementShopBuildingModel {
	if x != nil {
		return x.ShopModel
	}
	return nil
}

func (x *ElementShopInfo_S) GetHandbooks() []int32 {
	if x != nil {
		return x.Handbooks
	}
	return nil
}

//地上物商店购买记录结构体
type ElementShopBuildingModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId              int32                `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	ShopBuildingModels []*ShopBuildingModel `protobuf:"bytes,2,rep,name=shopBuildingModels,proto3" json:"shopBuildingModels,omitempty"`         //普通建筑商店购买列表-不包括装饰物
	DecorateeRewardIds []int32              `protobuf:"varint,3,rep,packed,name=decorateeRewardIds,proto3" json:"decorateeRewardIds,omitempty"` //装饰奖励领取id
}

func (x *ElementShopBuildingModel) Reset() {
	*x = ElementShopBuildingModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementShopBuildingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementShopBuildingModel) ProtoMessage() {}

func (x *ElementShopBuildingModel) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementShopBuildingModel.ProtoReflect.Descriptor instead.
func (*ElementShopBuildingModel) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{2}
}

func (x *ElementShopBuildingModel) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementShopBuildingModel) GetShopBuildingModels() []*ShopBuildingModel {
	if x != nil {
		return x.ShopBuildingModels
	}
	return nil
}

func (x *ElementShopBuildingModel) GetDecorateeRewardIds() []int32 {
	if x != nil {
		return x.DecorateeRewardIds
	}
	return nil
}

//建筑id，购买次数
type ShopBuildingModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid      int32 `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	BuyCount int32 `protobuf:"varint,2,opt,name=buyCount,proto3" json:"buyCount,omitempty"` //购买次数
}

func (x *ShopBuildingModel) Reset() {
	*x = ShopBuildingModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShopBuildingModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopBuildingModel) ProtoMessage() {}

func (x *ShopBuildingModel) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopBuildingModel.ProtoReflect.Descriptor instead.
func (*ShopBuildingModel) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{3}
}

func (x *ShopBuildingModel) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ShopBuildingModel) GetBuyCount() int32 {
	if x != nil {
		return x.BuyCount
	}
	return 0
}

//E_ElementShopBuy_C 购买地上物
type ElementShopBuyBuilding_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Tid   int32 `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
}

func (x *ElementShopBuyBuilding_C) Reset() {
	*x = ElementShopBuyBuilding_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementShopBuyBuilding_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementShopBuyBuilding_C) ProtoMessage() {}

func (x *ElementShopBuyBuilding_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementShopBuyBuilding_C.ProtoReflect.Descriptor instead.
func (*ElementShopBuyBuilding_C) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{4}
}

func (x *ElementShopBuyBuilding_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementShopBuyBuilding_C) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

type ElementShopBuyBuilding_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result    int32              `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MapId     int32              `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
	ShopModel *ShopBuildingModel `protobuf:"bytes,3,opt,name=shopModel,proto3" json:"shopModel,omitempty"` //购买信息
}

func (x *ElementShopBuyBuilding_S) Reset() {
	*x = ElementShopBuyBuilding_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementShopBuyBuilding_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementShopBuyBuilding_S) ProtoMessage() {}

func (x *ElementShopBuyBuilding_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementShopBuyBuilding_S.ProtoReflect.Descriptor instead.
func (*ElementShopBuyBuilding_S) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{5}
}

func (x *ElementShopBuyBuilding_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementShopBuyBuilding_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementShopBuyBuilding_S) GetShopModel() *ShopBuildingModel {
	if x != nil {
		return x.ShopModel
	}
	return nil
}

//E_ElementShopBuy_C 购买装饰物
type ElementShopBuyDecorate_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId  int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Tid    int32 `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	BuyNum int32 `protobuf:"varint,3,opt,name=buyNum,proto3" json:"buyNum,omitempty"`
}

func (x *ElementShopBuyDecorate_C) Reset() {
	*x = ElementShopBuyDecorate_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementShopBuyDecorate_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementShopBuyDecorate_C) ProtoMessage() {}

func (x *ElementShopBuyDecorate_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementShopBuyDecorate_C.ProtoReflect.Descriptor instead.
func (*ElementShopBuyDecorate_C) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{6}
}

func (x *ElementShopBuyDecorate_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementShopBuyDecorate_C) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ElementShopBuyDecorate_C) GetBuyNum() int32 {
	if x != nil {
		return x.BuyNum
	}
	return 0
}

//E_ElementShopBuy_S 只返回成功失败
type ElementShopBuyDecorate_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MapId  int32 `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementShopBuyDecorate_S) Reset() {
	*x = ElementShopBuyDecorate_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementShopBuyDecorate_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementShopBuyDecorate_S) ProtoMessage() {}

func (x *ElementShopBuyDecorate_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementShopBuyDecorate_S.ProtoReflect.Descriptor instead.
func (*ElementShopBuyDecorate_S) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{7}
}

func (x *ElementShopBuyDecorate_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementShopBuyDecorate_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

//E_ElementDecorateGroupReward_C 领取组奖励
type ElementDecorateGroupReward_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Tid   int32 `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
}

func (x *ElementDecorateGroupReward_C) Reset() {
	*x = ElementDecorateGroupReward_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementDecorateGroupReward_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementDecorateGroupReward_C) ProtoMessage() {}

func (x *ElementDecorateGroupReward_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementDecorateGroupReward_C.ProtoReflect.Descriptor instead.
func (*ElementDecorateGroupReward_C) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{8}
}

func (x *ElementDecorateGroupReward_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementDecorateGroupReward_C) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

type ElementDecorateGroupReward_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MapId  int32 `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementDecorateGroupReward_S) Reset() {
	*x = ElementDecorateGroupReward_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementshop_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementDecorateGroupReward_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementDecorateGroupReward_S) ProtoMessage() {}

func (x *ElementDecorateGroupReward_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementshop_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementDecorateGroupReward_S.ProtoReflect.Descriptor instead.
func (*ElementDecorateGroupReward_S) Descriptor() ([]byte, []int) {
	return file_msg_elementshop_proto_rawDescGZIP(), []int{9}
}

func (x *ElementDecorateGroupReward_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementDecorateGroupReward_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

var File_msg_elementshop_proto protoreflect.FileDescriptor

var file_msg_elementshop_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x73, 0x67, 0x2f, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x68, 0x6f,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x29, 0x0a, 0x11,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x5f,
	0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x9c, 0x01, 0x0a, 0x11, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x09, 0x73,
	0x68, 0x6f, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x70,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x09, 0x73,
	0x68, 0x6f, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x68, 0x61, 0x6e,
	0x64, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x22, 0xa8, 0x01, 0x0a, 0x18, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x46, 0x0a, 0x12, 0x73, 0x68, 0x6f,
	0x70, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x12, 0x73,
	0x68, 0x6f, 0x70, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x12, 0x2e, 0x0a, 0x12, 0x64, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74, 0x65, 0x65, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x12, 0x64,
	0x65, 0x63, 0x6f, 0x72, 0x61, 0x74, 0x65, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x64,
	0x73, 0x22, 0x41, 0x0a, 0x11, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e,
	0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x79, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x75, 0x79, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x42, 0x0a, 0x18, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x68, 0x6f, 0x70, 0x42, 0x75, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x43,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x22, 0x7e, 0x0a, 0x18, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x75, 0x79, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x69,
	0x6e, 0x67, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70,
	0x49, 0x64, 0x12, 0x34, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x09, 0x73,
	0x68, 0x6f, 0x70, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x5a, 0x0a, 0x18, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x42, 0x75, 0x79, 0x44, 0x65, 0x63, 0x6f, 0x72, 0x61,
	0x74, 0x65, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x62, 0x75, 0x79, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x62, 0x75,
	0x79, 0x4e, 0x75, 0x6d, 0x22, 0x48, 0x0a, 0x18, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x68, 0x6f, 0x70, 0x42, 0x75, 0x79, 0x44, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x46,
	0x0a, 0x1c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x43, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x61, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x1c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x44, 0x65, 0x63, 0x6f, 0x72, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d,
	0x61, 0x70, 0x49, 0x64, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_elementshop_proto_rawDescOnce sync.Once
	file_msg_elementshop_proto_rawDescData = file_msg_elementshop_proto_rawDesc
)

func file_msg_elementshop_proto_rawDescGZIP() []byte {
	file_msg_elementshop_proto_rawDescOnce.Do(func() {
		file_msg_elementshop_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_elementshop_proto_rawDescData)
	})
	return file_msg_elementshop_proto_rawDescData
}

var file_msg_elementshop_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_msg_elementshop_proto_goTypes = []interface{}{
	(*ElementShopInfo_C)(nil),            // 0: msg.ElementShopInfo_C
	(*ElementShopInfo_S)(nil),            // 1: msg.ElementShopInfo_S
	(*ElementShopBuildingModel)(nil),     // 2: msg.ElementShopBuildingModel
	(*ShopBuildingModel)(nil),            // 3: msg.ShopBuildingModel
	(*ElementShopBuyBuilding_C)(nil),     // 4: msg.ElementShopBuyBuilding_C
	(*ElementShopBuyBuilding_S)(nil),     // 5: msg.ElementShopBuyBuilding_S
	(*ElementShopBuyDecorate_C)(nil),     // 6: msg.ElementShopBuyDecorate_C
	(*ElementShopBuyDecorate_S)(nil),     // 7: msg.ElementShopBuyDecorate_S
	(*ElementDecorateGroupReward_C)(nil), // 8: msg.ElementDecorateGroupReward_C
	(*ElementDecorateGroupReward_S)(nil), // 9: msg.ElementDecorateGroupReward_S
}
var file_msg_elementshop_proto_depIdxs = []int32{
	2, // 0: msg.ElementShopInfo_S.shopModel:type_name -> msg.ElementShopBuildingModel
	3, // 1: msg.ElementShopBuildingModel.shopBuildingModels:type_name -> msg.ShopBuildingModel
	3, // 2: msg.ElementShopBuyBuilding_S.shopModel:type_name -> msg.ShopBuildingModel
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_msg_elementshop_proto_init() }
func file_msg_elementshop_proto_init() {
	if File_msg_elementshop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_elementshop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementShopInfo_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementshop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementShopInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementshop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementShopBuildingModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementshop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShopBuildingModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementshop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementShopBuyBuilding_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementshop_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementShopBuyBuilding_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementshop_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementShopBuyDecorate_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementshop_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementShopBuyDecorate_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementshop_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementDecorateGroupReward_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementshop_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementDecorateGroupReward_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_elementshop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_elementshop_proto_goTypes,
		DependencyIndexes: file_msg_elementshop_proto_depIdxs,
		MessageInfos:      file_msg_elementshop_proto_msgTypes,
	}.Build()
	File_msg_elementshop_proto = out.File
	file_msg_elementshop_proto_rawDesc = nil
	file_msg_elementshop_proto_goTypes = nil
	file_msg_elementshop_proto_depIdxs = nil
}
