// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msg/elementinfo.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ElementUpdateOp int32

const (
	ElementUpdateOp_ELEMENT_UPDATE ElementUpdateOp = 0 //数量更新
	ElementUpdateOp_ELEMENT_ADD    ElementUpdateOp = 1 //数量增加
	ElementUpdateOp_ELEMENT_DEL    ElementUpdateOp = 2 //数量减少
)

// Enum value maps for ElementUpdateOp.
var (
	ElementUpdateOp_name = map[int32]string{
		0: "ELEMENT_UPDATE",
		1: "ELEMENT_ADD",
		2: "ELEMENT_DEL",
	}
	ElementUpdateOp_value = map[string]int32{
		"ELEMENT_UPDATE": 0,
		"ELEMENT_ADD":    1,
		"ELEMENT_DEL":    2,
	}
)

func (x ElementUpdateOp) Enum() *ElementUpdateOp {
	p := new(ElementUpdateOp)
	*p = x
	return p
}

func (x ElementUpdateOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementUpdateOp) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_elementinfo_proto_enumTypes[0].Descriptor()
}

func (ElementUpdateOp) Type() protoreflect.EnumType {
	return &file_msg_elementinfo_proto_enumTypes[0]
}

func (x ElementUpdateOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementUpdateOp.Descriptor instead.
func (ElementUpdateOp) EnumDescriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{0}
}

//E_ElementBagInfo_C
type ElementBagInfo_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementBagInfo_C) Reset() {
	*x = ElementBagInfo_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementBagInfo_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementBagInfo_C) ProtoMessage() {}

func (x *ElementBagInfo_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementBagInfo_C.ProtoReflect.Descriptor instead.
func (*ElementBagInfo_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{0}
}

func (x *ElementBagInfo_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

//所有物品信息 E_ElementBagInfo_S
type ElementBagInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32            `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Bag    *ElementBagModel `protobuf:"bytes,2,opt,name=bag,proto3" json:"bag,omitempty"`
	Skins  []int32          `protobuf:"varint,3,rep,packed,name=skins,proto3" json:"skins,omitempty"` //拥有皮肤
}

func (x *ElementBagInfo_S) Reset() {
	*x = ElementBagInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementBagInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementBagInfo_S) ProtoMessage() {}

func (x *ElementBagInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementBagInfo_S.ProtoReflect.Descriptor instead.
func (*ElementBagInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{1}
}

func (x *ElementBagInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementBagInfo_S) GetBag() *ElementBagModel {
	if x != nil {
		return x.Bag
	}
	return nil
}

func (x *ElementBagInfo_S) GetSkins() []int32 {
	if x != nil {
		return x.Skins
	}
	return nil
}

type ElementAutoGenRewardInfo_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid   int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	MapId int32 `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementAutoGenRewardInfo_C) Reset() {
	*x = ElementAutoGenRewardInfo_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementAutoGenRewardInfo_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementAutoGenRewardInfo_C) ProtoMessage() {}

func (x *ElementAutoGenRewardInfo_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementAutoGenRewardInfo_C.ProtoReflect.Descriptor instead.
func (*ElementAutoGenRewardInfo_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{2}
}

func (x *ElementAutoGenRewardInfo_C) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementAutoGenRewardInfo_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type ElementAutoGenRewardInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32                           `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Sid    int32                           `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Reward []*ElementAutoGenItemRewardInfo `protobuf:"bytes,3,rep,name=reward,proto3" json:"reward,omitempty"`
}

func (x *ElementAutoGenRewardInfo_S) Reset() {
	*x = ElementAutoGenRewardInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementAutoGenRewardInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementAutoGenRewardInfo_S) ProtoMessage() {}

func (x *ElementAutoGenRewardInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementAutoGenRewardInfo_S.ProtoReflect.Descriptor instead.
func (*ElementAutoGenRewardInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{3}
}

func (x *ElementAutoGenRewardInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementAutoGenRewardInfo_S) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementAutoGenRewardInfo_S) GetReward() []*ElementAutoGenItemRewardInfo {
	if x != nil {
		return x.Reward
	}
	return nil
}

//不同地图的地上物背包
type ElementBagModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId  int32               `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Infos  []*ElementInfo      `protobuf:"bytes,2,rep,name=infos,proto3" json:"infos,omitempty"`
	Stacks []*ElementStackInfo `protobuf:"bytes,3,rep,name=stacks,proto3" json:"stacks,omitempty"` // 堆叠物
}

func (x *ElementBagModel) Reset() {
	*x = ElementBagModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementBagModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementBagModel) ProtoMessage() {}

func (x *ElementBagModel) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementBagModel.ProtoReflect.Descriptor instead.
func (*ElementBagModel) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{4}
}

func (x *ElementBagModel) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementBagModel) GetInfos() []*ElementInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *ElementBagModel) GetStacks() []*ElementStackInfo {
	if x != nil {
		return x.Stacks
	}
	return nil
}

//物品信息
type ElementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid          int32               `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Tid          int32               `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	LevelInfo    *ElementLevelInfo   `protobuf:"bytes,3,opt,name=levelInfo,proto3" json:"levelInfo,omitempty"`
	MakeInfo     *ElementMakeInfo    `protobuf:"bytes,4,opt,name=makeInfo,proto3" json:"makeInfo,omitempty"`
	AutoGenInfo  *ElementAutoGenInfo `protobuf:"bytes,5,opt,name=autoGenInfo,proto3" json:"autoGenInfo,omitempty"`
	ObstacleInfo *ObstacleInfo       `protobuf:"bytes,6,opt,name=obstacleInfo,proto3" json:"obstacleInfo,omitempty"` //障碍数据
}

func (x *ElementInfo) Reset() {
	*x = ElementInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementInfo) ProtoMessage() {}

func (x *ElementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementInfo.ProtoReflect.Descriptor instead.
func (*ElementInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{5}
}

func (x *ElementInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ElementInfo) GetLevelInfo() *ElementLevelInfo {
	if x != nil {
		return x.LevelInfo
	}
	return nil
}

func (x *ElementInfo) GetMakeInfo() *ElementMakeInfo {
	if x != nil {
		return x.MakeInfo
	}
	return nil
}

func (x *ElementInfo) GetAutoGenInfo() *ElementAutoGenInfo {
	if x != nil {
		return x.AutoGenInfo
	}
	return nil
}

func (x *ElementInfo) GetObstacleInfo() *ObstacleInfo {
	if x != nil {
		return x.ObstacleInfo
	}
	return nil
}

//障碍数据
type ObstacleInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CdInfo *CDInfo `protobuf:"bytes,1,opt,name=cdInfo,proto3" json:"cdInfo,omitempty"`
}

func (x *ObstacleInfo) Reset() {
	*x = ObstacleInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObstacleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObstacleInfo) ProtoMessage() {}

func (x *ObstacleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObstacleInfo.ProtoReflect.Descriptor instead.
func (*ObstacleInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{6}
}

func (x *ObstacleInfo) GetCdInfo() *CDInfo {
	if x != nil {
		return x.CdInfo
	}
	return nil
}

type ElementAutoGenInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RewardTime int64 `protobuf:"varint,1,opt,name=rewardTime,proto3" json:"rewardTime,omitempty"` //领取时间
}

func (x *ElementAutoGenInfo) Reset() {
	*x = ElementAutoGenInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementAutoGenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementAutoGenInfo) ProtoMessage() {}

func (x *ElementAutoGenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementAutoGenInfo.ProtoReflect.Descriptor instead.
func (*ElementAutoGenInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{7}
}

func (x *ElementAutoGenInfo) GetRewardTime() int64 {
	if x != nil {
		return x.RewardTime
	}
	return 0
}

type ElementStackInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid   int32 `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ElementStackInfo) Reset() {
	*x = ElementStackInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementStackInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementStackInfo) ProtoMessage() {}

func (x *ElementStackInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementStackInfo.ProtoReflect.Descriptor instead.
func (*ElementStackInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{8}
}

func (x *ElementStackInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ElementStackInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ElementMakeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartTime int32 `protobuf:"varint,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	// Deprecated: Do not use.
	ItemIds  []int32              `protobuf:"varint,2,rep,packed,name=itemIds,proto3" json:"itemIds,omitempty"`
	BuyCount int32                `protobuf:"varint,3,opt,name=buyCount,proto3" json:"buyCount,omitempty"` //购买格子次数
	Infos    []*ElementMakeCdInfo `protobuf:"bytes,4,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *ElementMakeInfo) Reset() {
	*x = ElementMakeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMakeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMakeInfo) ProtoMessage() {}

func (x *ElementMakeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMakeInfo.ProtoReflect.Descriptor instead.
func (*ElementMakeInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{9}
}

func (x *ElementMakeInfo) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

// Deprecated: Do not use.
func (x *ElementMakeInfo) GetItemIds() []int32 {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *ElementMakeInfo) GetBuyCount() int32 {
	if x != nil {
		return x.BuyCount
	}
	return 0
}

func (x *ElementMakeInfo) GetInfos() []*ElementMakeCdInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type ElementMakeCdInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid int32 `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Cd  int32 `protobuf:"varint,2,opt,name=cd,proto3" json:"cd,omitempty"`
}

func (x *ElementMakeCdInfo) Reset() {
	*x = ElementMakeCdInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMakeCdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMakeCdInfo) ProtoMessage() {}

func (x *ElementMakeCdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMakeCdInfo.ProtoReflect.Descriptor instead.
func (*ElementMakeCdInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{10}
}

func (x *ElementMakeCdInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ElementMakeCdInfo) GetCd() int32 {
	if x != nil {
		return x.Cd
	}
	return 0
}

//物品等级信息
type ElementLevelInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level int32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	// Deprecated: Do not use.
	StartTime int32   `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime,omitempty"` //开始时间
	CdInfo    *CDInfo `protobuf:"bytes,3,opt,name=cdInfo,proto3" json:"cdInfo,omitempty"`
}

func (x *ElementLevelInfo) Reset() {
	*x = ElementLevelInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementLevelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementLevelInfo) ProtoMessage() {}

func (x *ElementLevelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementLevelInfo.ProtoReflect.Descriptor instead.
func (*ElementLevelInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{11}
}

func (x *ElementLevelInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// Deprecated: Do not use.
func (x *ElementLevelInfo) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ElementLevelInfo) GetCdInfo() *CDInfo {
	if x != nil {
		return x.CdInfo
	}
	return nil
}

type ElementAutoGenItemRewardInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid   int32 `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	Count int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ElementAutoGenItemRewardInfo) Reset() {
	*x = ElementAutoGenItemRewardInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementAutoGenItemRewardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementAutoGenItemRewardInfo) ProtoMessage() {}

func (x *ElementAutoGenItemRewardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementAutoGenItemRewardInfo.ProtoReflect.Descriptor instead.
func (*ElementAutoGenItemRewardInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{12}
}

func (x *ElementAutoGenItemRewardInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ElementAutoGenItemRewardInfo) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

//物品更新或新增 ELEMENTUPDATE_S
type ElementUpdate_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32                      `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MapId  int32                      `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Infos  []*ElementUpdateModel      `protobuf:"bytes,3,rep,name=infos,proto3" json:"infos,omitempty"`
	Stacks []*ElementStackUpdateModel `protobuf:"bytes,4,rep,name=stacks,proto3" json:"stacks,omitempty"`
}

func (x *ElementUpdate_S) Reset() {
	*x = ElementUpdate_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementUpdate_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementUpdate_S) ProtoMessage() {}

func (x *ElementUpdate_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementUpdate_S.ProtoReflect.Descriptor instead.
func (*ElementUpdate_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{13}
}

func (x *ElementUpdate_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementUpdate_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementUpdate_S) GetInfos() []*ElementUpdateModel {
	if x != nil {
		return x.Infos
	}
	return nil
}

func (x *ElementUpdate_S) GetStacks() []*ElementStackUpdateModel {
	if x != nil {
		return x.Stacks
	}
	return nil
}

type ElementUpdateModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op    ElementUpdateOp `protobuf:"varint,1,opt,name=op,proto3,enum=msg.ElementUpdateOp" json:"op,omitempty"`
	Infos *ElementInfo    `protobuf:"bytes,2,opt,name=infos,proto3" json:"infos,omitempty"`
}

func (x *ElementUpdateModel) Reset() {
	*x = ElementUpdateModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementUpdateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementUpdateModel) ProtoMessage() {}

func (x *ElementUpdateModel) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementUpdateModel.ProtoReflect.Descriptor instead.
func (*ElementUpdateModel) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{14}
}

func (x *ElementUpdateModel) GetOp() ElementUpdateOp {
	if x != nil {
		return x.Op
	}
	return ElementUpdateOp_ELEMENT_UPDATE
}

func (x *ElementUpdateModel) GetInfos() *ElementInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type ElementStackUpdateModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op    ElementUpdateOp `protobuf:"varint,1,opt,name=op,proto3,enum=msg.ElementUpdateOp" json:"op,omitempty"`
	Tid   int32           `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	Count int32           `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *ElementStackUpdateModel) Reset() {
	*x = ElementStackUpdateModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementStackUpdateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementStackUpdateModel) ProtoMessage() {}

func (x *ElementStackUpdateModel) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementStackUpdateModel.ProtoReflect.Descriptor instead.
func (*ElementStackUpdateModel) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{15}
}

func (x *ElementStackUpdateModel) GetOp() ElementUpdateOp {
	if x != nil {
		return x.Op
	}
	return ElementUpdateOp_ELEMENT_UPDATE
}

func (x *ElementStackUpdateModel) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ElementStackUpdateModel) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

//ELEMENTLEVELUP_C
type ElementLevelUp_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid   int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	MapId int32 `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementLevelUp_C) Reset() {
	*x = ElementLevelUp_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementLevelUp_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementLevelUp_C) ProtoMessage() {}

func (x *ElementLevelUp_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementLevelUp_C.ProtoReflect.Descriptor instead.
func (*ElementLevelUp_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{16}
}

func (x *ElementLevelUp_C) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementLevelUp_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

//ELEMENTLEVELUP_S
type ElementLevelUp_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32        `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Sid    int32        `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	MapId  int32        `protobuf:"varint,3,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Info   *ElementInfo `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ElementLevelUp_S) Reset() {
	*x = ElementLevelUp_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementLevelUp_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementLevelUp_S) ProtoMessage() {}

func (x *ElementLevelUp_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementLevelUp_S.ProtoReflect.Descriptor instead.
func (*ElementLevelUp_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{17}
}

func (x *ElementLevelUp_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementLevelUp_S) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementLevelUp_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementLevelUp_S) GetInfo() *ElementInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

//E_ElementLevelUpFinish_C
type ElementLevelUpFinish_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid   int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	MapId int32 `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementLevelUpFinish_C) Reset() {
	*x = ElementLevelUpFinish_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementLevelUpFinish_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementLevelUpFinish_C) ProtoMessage() {}

func (x *ElementLevelUpFinish_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementLevelUpFinish_C.ProtoReflect.Descriptor instead.
func (*ElementLevelUpFinish_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{18}
}

func (x *ElementLevelUpFinish_C) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementLevelUpFinish_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type ElementLevelUpFinish_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32        `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Sid    int32        `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	MapId  int32        `protobuf:"varint,3,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Info   *ElementInfo `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ElementLevelUpFinish_S) Reset() {
	*x = ElementLevelUpFinish_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementLevelUpFinish_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementLevelUpFinish_S) ProtoMessage() {}

func (x *ElementLevelUpFinish_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementLevelUpFinish_S.ProtoReflect.Descriptor instead.
func (*ElementLevelUpFinish_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{19}
}

func (x *ElementLevelUpFinish_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementLevelUpFinish_S) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementLevelUpFinish_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementLevelUpFinish_S) GetInfo() *ElementInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

//自动生产物品，领取奖励
type ElementAutoReward_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sids  []int32 `protobuf:"varint,1,rep,packed,name=sids,proto3" json:"sids,omitempty"`
	MapId int32   `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementAutoReward_C) Reset() {
	*x = ElementAutoReward_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementAutoReward_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementAutoReward_C) ProtoMessage() {}

func (x *ElementAutoReward_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementAutoReward_C.ProtoReflect.Descriptor instead.
func (*ElementAutoReward_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{20}
}

func (x *ElementAutoReward_C) GetSids() []int32 {
	if x != nil {
		return x.Sids
	}
	return nil
}

func (x *ElementAutoReward_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type ElementAutoReward_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Sids   []int32 `protobuf:"varint,2,rep,packed,name=sids,proto3" json:"sids,omitempty"`
}

func (x *ElementAutoReward_S) Reset() {
	*x = ElementAutoReward_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementAutoReward_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementAutoReward_S) ProtoMessage() {}

func (x *ElementAutoReward_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementAutoReward_S.ProtoReflect.Descriptor instead.
func (*ElementAutoReward_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{21}
}

func (x *ElementAutoReward_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementAutoReward_S) GetSids() []int32 {
	if x != nil {
		return x.Sids
	}
	return nil
}

//生产道具请求
type ElementMakeItem_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid     int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	ItemId  int32 `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Num     int32 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	MapId   int32 `protobuf:"varint,4,opt,name=mapId,proto3" json:"mapId,omitempty"`
	HeroTid int32 `protobuf:"varint,5,opt,name=heroTid,proto3" json:"heroTid,omitempty"` //工作英雄id
}

func (x *ElementMakeItem_C) Reset() {
	*x = ElementMakeItem_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMakeItem_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMakeItem_C) ProtoMessage() {}

func (x *ElementMakeItem_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMakeItem_C.ProtoReflect.Descriptor instead.
func (*ElementMakeItem_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{22}
}

func (x *ElementMakeItem_C) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementMakeItem_C) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ElementMakeItem_C) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ElementMakeItem_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementMakeItem_C) GetHeroTid() int32 {
	if x != nil {
		return x.HeroTid
	}
	return 0
}

//生产道具请求
type ElementMakeItem_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   int32                `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ItemInfo *ElementMakeItemInfo `protobuf:"bytes,2,opt,name=itemInfo,proto3" json:"itemInfo,omitempty"`
}

func (x *ElementMakeItem_S) Reset() {
	*x = ElementMakeItem_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMakeItem_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMakeItem_S) ProtoMessage() {}

func (x *ElementMakeItem_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMakeItem_S.ProtoReflect.Descriptor instead.
func (*ElementMakeItem_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{23}
}

func (x *ElementMakeItem_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementMakeItem_S) GetItemInfo() *ElementMakeItemInfo {
	if x != nil {
		return x.ItemInfo
	}
	return nil
}

//删除生产道具请求
type ElementCancelMakeItem_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid   int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Index int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // -1 取消所有
	MapId int32 `protobuf:"varint,3,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementCancelMakeItem_C) Reset() {
	*x = ElementCancelMakeItem_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementCancelMakeItem_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementCancelMakeItem_C) ProtoMessage() {}

func (x *ElementCancelMakeItem_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementCancelMakeItem_C.ProtoReflect.Descriptor instead.
func (*ElementCancelMakeItem_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{24}
}

func (x *ElementCancelMakeItem_C) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementCancelMakeItem_C) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ElementCancelMakeItem_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

//删除生产道具请求
type ElementCancelMakeItem_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   int32                `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ItemInfo *ElementMakeItemInfo `protobuf:"bytes,2,opt,name=itemInfo,proto3" json:"itemInfo,omitempty"`
}

func (x *ElementCancelMakeItem_S) Reset() {
	*x = ElementCancelMakeItem_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementCancelMakeItem_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementCancelMakeItem_S) ProtoMessage() {}

func (x *ElementCancelMakeItem_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementCancelMakeItem_S.ProtoReflect.Descriptor instead.
func (*ElementCancelMakeItem_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{25}
}

func (x *ElementCancelMakeItem_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementCancelMakeItem_S) GetItemInfo() *ElementMakeItemInfo {
	if x != nil {
		return x.ItemInfo
	}
	return nil
}

type ElementMakeItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid      int32            `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	MakeInfo *ElementMakeInfo `protobuf:"bytes,2,opt,name=makeInfo,proto3" json:"makeInfo,omitempty"`
}

func (x *ElementMakeItemInfo) Reset() {
	*x = ElementMakeItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMakeItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMakeItemInfo) ProtoMessage() {}

func (x *ElementMakeItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMakeItemInfo.ProtoReflect.Descriptor instead.
func (*ElementMakeItemInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{26}
}

func (x *ElementMakeItemInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementMakeItemInfo) GetMakeInfo() *ElementMakeInfo {
	if x != nil {
		return x.MakeInfo
	}
	return nil
}

//批量领取生产道具
type ElementMakeRewards_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32   `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Sids  []int32 `protobuf:"varint,2,rep,packed,name=sids,proto3" json:"sids,omitempty"`
}

func (x *ElementMakeRewards_C) Reset() {
	*x = ElementMakeRewards_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMakeRewards_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMakeRewards_C) ProtoMessage() {}

func (x *ElementMakeRewards_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMakeRewards_C.ProtoReflect.Descriptor instead.
func (*ElementMakeRewards_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{27}
}

func (x *ElementMakeRewards_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementMakeRewards_C) GetSids() []int32 {
	if x != nil {
		return x.Sids
	}
	return nil
}

type ElementMakeRewards_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MapId  int32                  `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Infos  []*ElementMakeItemInfo `protobuf:"bytes,3,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *ElementMakeRewards_S) Reset() {
	*x = ElementMakeRewards_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMakeRewards_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMakeRewards_S) ProtoMessage() {}

func (x *ElementMakeRewards_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMakeRewards_S.ProtoReflect.Descriptor instead.
func (*ElementMakeRewards_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{28}
}

func (x *ElementMakeRewards_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementMakeRewards_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ElementMakeRewards_S) GetInfos() []*ElementMakeItemInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

//生产道具槽位购买请求
type ElementMakeBuySlot_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid   int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	MapId int32 `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *ElementMakeBuySlot_C) Reset() {
	*x = ElementMakeBuySlot_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMakeBuySlot_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMakeBuySlot_C) ProtoMessage() {}

func (x *ElementMakeBuySlot_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMakeBuySlot_C.ProtoReflect.Descriptor instead.
func (*ElementMakeBuySlot_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{29}
}

func (x *ElementMakeBuySlot_C) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementMakeBuySlot_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type ElementMakeBuySlot_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Sid      int32 `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	BuyCount int32 `protobuf:"varint,3,opt,name=buyCount,proto3" json:"buyCount,omitempty"`
}

func (x *ElementMakeBuySlot_S) Reset() {
	*x = ElementMakeBuySlot_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementMakeBuySlot_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementMakeBuySlot_S) ProtoMessage() {}

func (x *ElementMakeBuySlot_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementMakeBuySlot_S.ProtoReflect.Descriptor instead.
func (*ElementMakeBuySlot_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{30}
}

func (x *ElementMakeBuySlot_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ElementMakeBuySlot_S) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementMakeBuySlot_S) GetBuyCount() int32 {
	if x != nil {
		return x.BuyCount
	}
	return 0
}

type MakeItemInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId int32 `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Time   int32 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *MakeItemInfo) Reset() {
	*x = MakeItemInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakeItemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeItemInfo) ProtoMessage() {}

func (x *MakeItemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeItemInfo.ProtoReflect.Descriptor instead.
func (*MakeItemInfo) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{31}
}

func (x *MakeItemInfo) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MakeItemInfo) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

//获取图鉴信息--获得新建筑后客户端自行判断添加，服务器不进行图鉴消息下发
type GetHandbooks_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *GetHandbooks_C) Reset() {
	*x = GetHandbooks_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHandbooks_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandbooks_C) ProtoMessage() {}

func (x *GetHandbooks_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandbooks_C.ProtoReflect.Descriptor instead.
func (*GetHandbooks_C) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{32}
}

func (x *GetHandbooks_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

type GetHandbooks_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result    int32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MapId     int32   `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Handbooks []int32 `protobuf:"varint,3,rep,packed,name=handbooks,proto3" json:"handbooks,omitempty"` //图鉴列表
}

func (x *GetHandbooks_S) Reset() {
	*x = GetHandbooks_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_elementinfo_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHandbooks_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHandbooks_S) ProtoMessage() {}

func (x *GetHandbooks_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_elementinfo_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHandbooks_S.ProtoReflect.Descriptor instead.
func (*GetHandbooks_S) Descriptor() ([]byte, []int) {
	return file_msg_elementinfo_proto_rawDescGZIP(), []int{33}
}

func (x *GetHandbooks_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *GetHandbooks_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *GetHandbooks_S) GetHandbooks() []int32 {
	if x != nil {
		return x.Handbooks
	}
	return nil
}

var File_msg_elementinfo_proto protoreflect.FileDescriptor

var file_msg_elementinfo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x73, 0x67, 0x2f, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x10, 0x6d, 0x73,
	0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28,
	0x0a, 0x10, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f,
	0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x68, 0x0a, 0x10, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x42, 0x61, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x03, 0x62, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42,
	0x61, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x03, 0x62, 0x61, 0x67, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x6b, 0x69, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x73, 0x6b, 0x69,
	0x6e, 0x73, 0x22, 0x44, 0x0a, 0x1a, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74,
	0x6f, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x43,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x81, 0x01, 0x0a, 0x1a, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x6f, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x77, 0x61, 0x72,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69,
	0x64, 0x12, 0x39, 0x0a, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41,
	0x75, 0x74, 0x6f, 0x47, 0x65, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x22, 0x7e, 0x0a, 0x0f,
	0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x61, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x2d, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x63, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x74, 0x61, 0x63, 0x6b, 0x73, 0x22, 0x8a, 0x02, 0x0a,
	0x0b, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64,
	0x12, 0x33, 0x0a, 0x09, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x6c, 0x65, 0x76, 0x65,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6d,
	0x61, 0x6b, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x39, 0x0a, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x47,
	0x65, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x6f, 0x47, 0x65,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x61, 0x75, 0x74, 0x6f, 0x47, 0x65, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x35, 0x0a, 0x0c, 0x6f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f,
	0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x6f, 0x62, 0x73,
	0x74, 0x61, 0x63, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x33, 0x0a, 0x0c, 0x4f, 0x62, 0x73,
	0x74, 0x61, 0x63, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x06, 0x63, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x43, 0x44, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x63, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x34,
	0x0a, 0x12, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x6f, 0x47, 0x65, 0x6e,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x10, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x63, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x97, 0x01, 0x0a, 0x0f, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x05, 0x42, 0x02, 0x18, 0x01, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x62, 0x75, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x05,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x35, 0x0a, 0x11, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x63,
	0x64, 0x22, 0x6f, 0x0a, 0x10, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x20, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x42, 0x02,
	0x18, 0x01, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x06, 0x63, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x43, 0x44, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x63, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x46, 0x0a, 0x1c, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74,
	0x6f, 0x47, 0x65, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x74, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa4, 0x01, 0x0a, 0x0f, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x53, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x05,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d,
	0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x63, 0x6b, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x06, 0x73, 0x74, 0x61, 0x63, 0x6b,
	0x73, 0x22, 0x62, 0x0a, 0x12, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x24, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x26, 0x0a,
	0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x67, 0x0a, 0x17, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x63, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x24, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a,
	0x0a, 0x10, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70,
	0x5f, 0x43, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x10, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x5f, 0x53, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x24,
	0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x22, 0x40, 0x0a, 0x16, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x43, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x7e, 0x0a, 0x16, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61,
	0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x3f, 0x0a, 0x13, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x43, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x64,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x13, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x41, 0x75, 0x74, 0x6f, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x53, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x64, 0x73, 0x22, 0x7f, 0x0a, 0x11, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x43, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x61, 0x70, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x22, 0x61, 0x0a, 0x11, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x73, 0x67,
	0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x57,
	0x0a, 0x17, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4d,
	0x61, 0x6b, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x43, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x67, 0x0a, 0x17, 0x45, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4d, 0x61, 0x6b, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x69, 0x74,
	0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f,
	0x22, 0x59, 0x0a, 0x13, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x6d, 0x61, 0x6b,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x08, 0x6d, 0x61, 0x6b, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x40, 0x0a, 0x14, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x73, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x64, 0x73, 0x22, 0x74, 0x0a,
	0x14, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x73, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61,
	0x70, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x4d, 0x61, 0x6b, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e,
	0x66, 0x6f, 0x73, 0x22, 0x3e, 0x0a, 0x14, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61,
	0x6b, 0x65, 0x42, 0x75, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x5f, 0x43, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61,
	0x70, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x14, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61,
	0x6b, 0x65, 0x42, 0x75, 0x79, 0x53, 0x6c, 0x6f, 0x74, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x75, 0x79, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x62, 0x75, 0x79, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x22, 0x3a, 0x0a, 0x0c, 0x4d, 0x61, 0x6b, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x26, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x5f, 0x43, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6d, 0x61, 0x70, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x6e, 0x64,
	0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x62, 0x6f, 0x6f,
	0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x62, 0x6f,
	0x6f, 0x6b, 0x73, 0x2a, 0x47, 0x0a, 0x0f, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4c, 0x45, 0x4d, 0x45, 0x4e,
	0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x4c,
	0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x45,
	0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x45, 0x4c, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_elementinfo_proto_rawDescOnce sync.Once
	file_msg_elementinfo_proto_rawDescData = file_msg_elementinfo_proto_rawDesc
)

func file_msg_elementinfo_proto_rawDescGZIP() []byte {
	file_msg_elementinfo_proto_rawDescOnce.Do(func() {
		file_msg_elementinfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_elementinfo_proto_rawDescData)
	})
	return file_msg_elementinfo_proto_rawDescData
}

var file_msg_elementinfo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_elementinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_msg_elementinfo_proto_goTypes = []interface{}{
	(ElementUpdateOp)(0),                 // 0: msg.ElementUpdateOp
	(*ElementBagInfo_C)(nil),             // 1: msg.ElementBagInfo_C
	(*ElementBagInfo_S)(nil),             // 2: msg.ElementBagInfo_S
	(*ElementAutoGenRewardInfo_C)(nil),   // 3: msg.ElementAutoGenRewardInfo_C
	(*ElementAutoGenRewardInfo_S)(nil),   // 4: msg.ElementAutoGenRewardInfo_S
	(*ElementBagModel)(nil),              // 5: msg.ElementBagModel
	(*ElementInfo)(nil),                  // 6: msg.ElementInfo
	(*ObstacleInfo)(nil),                 // 7: msg.ObstacleInfo
	(*ElementAutoGenInfo)(nil),           // 8: msg.ElementAutoGenInfo
	(*ElementStackInfo)(nil),             // 9: msg.ElementStackInfo
	(*ElementMakeInfo)(nil),              // 10: msg.ElementMakeInfo
	(*ElementMakeCdInfo)(nil),            // 11: msg.ElementMakeCdInfo
	(*ElementLevelInfo)(nil),             // 12: msg.ElementLevelInfo
	(*ElementAutoGenItemRewardInfo)(nil), // 13: msg.ElementAutoGenItemRewardInfo
	(*ElementUpdate_S)(nil),              // 14: msg.ElementUpdate_S
	(*ElementUpdateModel)(nil),           // 15: msg.ElementUpdateModel
	(*ElementStackUpdateModel)(nil),      // 16: msg.ElementStackUpdateModel
	(*ElementLevelUp_C)(nil),             // 17: msg.ElementLevelUp_C
	(*ElementLevelUp_S)(nil),             // 18: msg.ElementLevelUp_S
	(*ElementLevelUpFinish_C)(nil),       // 19: msg.ElementLevelUpFinish_C
	(*ElementLevelUpFinish_S)(nil),       // 20: msg.ElementLevelUpFinish_S
	(*ElementAutoReward_C)(nil),          // 21: msg.ElementAutoReward_C
	(*ElementAutoReward_S)(nil),          // 22: msg.ElementAutoReward_S
	(*ElementMakeItem_C)(nil),            // 23: msg.ElementMakeItem_C
	(*ElementMakeItem_S)(nil),            // 24: msg.ElementMakeItem_S
	(*ElementCancelMakeItem_C)(nil),      // 25: msg.ElementCancelMakeItem_C
	(*ElementCancelMakeItem_S)(nil),      // 26: msg.ElementCancelMakeItem_S
	(*ElementMakeItemInfo)(nil),          // 27: msg.ElementMakeItemInfo
	(*ElementMakeRewards_C)(nil),         // 28: msg.ElementMakeRewards_C
	(*ElementMakeRewards_S)(nil),         // 29: msg.ElementMakeRewards_S
	(*ElementMakeBuySlot_C)(nil),         // 30: msg.ElementMakeBuySlot_C
	(*ElementMakeBuySlot_S)(nil),         // 31: msg.ElementMakeBuySlot_S
	(*MakeItemInfo)(nil),                 // 32: msg.MakeItemInfo
	(*GetHandbooks_C)(nil),               // 33: msg.GetHandbooks_C
	(*GetHandbooks_S)(nil),               // 34: msg.GetHandbooks_S
	(*CDInfo)(nil),                       // 35: msg.CDInfo
}
var file_msg_elementinfo_proto_depIdxs = []int32{
	5,  // 0: msg.ElementBagInfo_S.bag:type_name -> msg.ElementBagModel
	13, // 1: msg.ElementAutoGenRewardInfo_S.reward:type_name -> msg.ElementAutoGenItemRewardInfo
	6,  // 2: msg.ElementBagModel.infos:type_name -> msg.ElementInfo
	9,  // 3: msg.ElementBagModel.stacks:type_name -> msg.ElementStackInfo
	12, // 4: msg.ElementInfo.levelInfo:type_name -> msg.ElementLevelInfo
	10, // 5: msg.ElementInfo.makeInfo:type_name -> msg.ElementMakeInfo
	8,  // 6: msg.ElementInfo.autoGenInfo:type_name -> msg.ElementAutoGenInfo
	7,  // 7: msg.ElementInfo.obstacleInfo:type_name -> msg.ObstacleInfo
	35, // 8: msg.ObstacleInfo.cdInfo:type_name -> msg.CDInfo
	11, // 9: msg.ElementMakeInfo.infos:type_name -> msg.ElementMakeCdInfo
	35, // 10: msg.ElementLevelInfo.cdInfo:type_name -> msg.CDInfo
	15, // 11: msg.ElementUpdate_S.infos:type_name -> msg.ElementUpdateModel
	16, // 12: msg.ElementUpdate_S.stacks:type_name -> msg.ElementStackUpdateModel
	0,  // 13: msg.ElementUpdateModel.op:type_name -> msg.ElementUpdateOp
	6,  // 14: msg.ElementUpdateModel.infos:type_name -> msg.ElementInfo
	0,  // 15: msg.ElementStackUpdateModel.op:type_name -> msg.ElementUpdateOp
	6,  // 16: msg.ElementLevelUp_S.info:type_name -> msg.ElementInfo
	6,  // 17: msg.ElementLevelUpFinish_S.info:type_name -> msg.ElementInfo
	27, // 18: msg.ElementMakeItem_S.itemInfo:type_name -> msg.ElementMakeItemInfo
	27, // 19: msg.ElementCancelMakeItem_S.itemInfo:type_name -> msg.ElementMakeItemInfo
	10, // 20: msg.ElementMakeItemInfo.makeInfo:type_name -> msg.ElementMakeInfo
	27, // 21: msg.ElementMakeRewards_S.infos:type_name -> msg.ElementMakeItemInfo
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_msg_elementinfo_proto_init() }
func file_msg_elementinfo_proto_init() {
	if File_msg_elementinfo_proto != nil {
		return
	}
	file_msg_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_elementinfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementBagInfo_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementBagInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementAutoGenRewardInfo_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementAutoGenRewardInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementBagModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObstacleInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementAutoGenInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementStackInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMakeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMakeCdInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementLevelInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementAutoGenItemRewardInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementUpdate_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementUpdateModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementStackUpdateModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementLevelUp_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementLevelUp_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementLevelUpFinish_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementLevelUpFinish_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementAutoReward_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementAutoReward_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMakeItem_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMakeItem_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementCancelMakeItem_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementCancelMakeItem_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMakeItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMakeRewards_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMakeRewards_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMakeBuySlot_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementMakeBuySlot_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakeItemInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHandbooks_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_elementinfo_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHandbooks_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_elementinfo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_elementinfo_proto_goTypes,
		DependencyIndexes: file_msg_elementinfo_proto_depIdxs,
		EnumInfos:         file_msg_elementinfo_proto_enumTypes,
		MessageInfos:      file_msg_elementinfo_proto_msgTypes,
	}.Build()
	File_msg_elementinfo_proto = out.File
	file_msg_elementinfo_proto_rawDesc = nil
	file_msg_elementinfo_proto_goTypes = nil
	file_msg_elementinfo_proto_depIdxs = nil
}
