// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msg/hero.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeroWorkingStatus int32

const (
	HeroWorkingStatus_HERO_WORKING_IDLE      HeroWorkingStatus = 0 //空闲
	HeroWorkingStatus_HERO_WORKING_MAKE_ITEM HeroWorkingStatus = 1 //地上物制作道具
	HeroWorkingStatus_HERO_WORKING_OBSTACLE  HeroWorkingStatus = 2 //障碍
)

// Enum value maps for HeroWorkingStatus.
var (
	HeroWorkingStatus_name = map[int32]string{
		0: "HERO_WORKING_IDLE",
		1: "HERO_WORKING_MAKE_ITEM",
		2: "HERO_WORKING_OBSTACLE",
	}
	HeroWorkingStatus_value = map[string]int32{
		"HERO_WORKING_IDLE":      0,
		"HERO_WORKING_MAKE_ITEM": 1,
		"HERO_WORKING_OBSTACLE":  2,
	}
)

func (x HeroWorkingStatus) Enum() *HeroWorkingStatus {
	p := new(HeroWorkingStatus)
	*p = x
	return p
}

func (x HeroWorkingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeroWorkingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_hero_proto_enumTypes[0].Descriptor()
}

func (HeroWorkingStatus) Type() protoreflect.EnumType {
	return &file_msg_hero_proto_enumTypes[0]
}

func (x HeroWorkingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeroWorkingStatus.Descriptor instead.
func (HeroWorkingStatus) EnumDescriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{0}
}

type HeroInfo_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HeroInfo_C) Reset() {
	*x = HeroInfo_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroInfo_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroInfo_C) ProtoMessage() {}

func (x *HeroInfo_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroInfo_C.ProtoReflect.Descriptor instead.
func (*HeroInfo_C) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{0}
}

//英雄信息
type HeroInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32          `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Heros  []*HeroInfoMsg `protobuf:"bytes,2,rep,name=heros,proto3" json:"heros,omitempty"`
}

func (x *HeroInfo_S) Reset() {
	*x = HeroInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroInfo_S) ProtoMessage() {}

func (x *HeroInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroInfo_S.ProtoReflect.Descriptor instead.
func (*HeroInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{1}
}

func (x *HeroInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *HeroInfo_S) GetHeros() []*HeroInfoMsg {
	if x != nil {
		return x.Heros
	}
	return nil
}

//英雄信息
type HeroInfoChange_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32          `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Heros  []*HeroInfoMsg `protobuf:"bytes,2,rep,name=heros,proto3" json:"heros,omitempty"`
}

func (x *HeroInfoChange_S) Reset() {
	*x = HeroInfoChange_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroInfoChange_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroInfoChange_S) ProtoMessage() {}

func (x *HeroInfoChange_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroInfoChange_S.ProtoReflect.Descriptor instead.
func (*HeroInfoChange_S) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{2}
}

func (x *HeroInfoChange_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *HeroInfoChange_S) GetHeros() []*HeroInfoMsg {
	if x != nil {
		return x.Heros
	}
	return nil
}

type HeroInfoMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroTid       int32                 `protobuf:"varint,1,opt,name=heroTid,proto3" json:"heroTid,omitempty"` //配置id
	Level         int32                 `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`     //等级
	Exp           int32                 `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
	Star          int32                 `protobuf:"varint,4,opt,name=star,proto3" json:"star,omitempty"` //星级
	SkilLevel     int32                 `protobuf:"varint,5,opt,name=skilLevel,proto3" json:"skilLevel,omitempty"`
	Equips        map[int32]int32       `protobuf:"bytes,6,rep,name=equips,proto3" json:"equips,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //<index， equipUid>
	FashionId     int32                 `protobuf:"varint,7,opt,name=fashionId,proto3" json:"fashionId,omitempty"`                                                                                    //时装id，为0时使用默认时装
	WorkingStatus *HeroWorkingStatusMsg `protobuf:"bytes,8,opt,name=workingStatus,proto3" json:"workingStatus,omitempty"`                                                                             //工作状态 1:工作,0:空闲
}

func (x *HeroInfoMsg) Reset() {
	*x = HeroInfoMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroInfoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroInfoMsg) ProtoMessage() {}

func (x *HeroInfoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroInfoMsg.ProtoReflect.Descriptor instead.
func (*HeroInfoMsg) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{3}
}

func (x *HeroInfoMsg) GetHeroTid() int32 {
	if x != nil {
		return x.HeroTid
	}
	return 0
}

func (x *HeroInfoMsg) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *HeroInfoMsg) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *HeroInfoMsg) GetStar() int32 {
	if x != nil {
		return x.Star
	}
	return 0
}

func (x *HeroInfoMsg) GetSkilLevel() int32 {
	if x != nil {
		return x.SkilLevel
	}
	return 0
}

func (x *HeroInfoMsg) GetEquips() map[int32]int32 {
	if x != nil {
		return x.Equips
	}
	return nil
}

func (x *HeroInfoMsg) GetFashionId() int32 {
	if x != nil {
		return x.FashionId
	}
	return 0
}

func (x *HeroInfoMsg) GetWorkingStatus() *HeroWorkingStatusMsg {
	if x != nil {
		return x.WorkingStatus
	}
	return nil
}

type HeroWorkingStatusMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkingStatus int32   `protobuf:"varint,1,opt,name=workingStatus,proto3" json:"workingStatus,omitempty"` //工作状态 HeroWorkingStatus枚举
	Params        []int32 `protobuf:"varint,2,rep,packed,name=params,proto3" json:"params,omitempty"`
}

func (x *HeroWorkingStatusMsg) Reset() {
	*x = HeroWorkingStatusMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroWorkingStatusMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroWorkingStatusMsg) ProtoMessage() {}

func (x *HeroWorkingStatusMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroWorkingStatusMsg.ProtoReflect.Descriptor instead.
func (*HeroWorkingStatusMsg) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{4}
}

func (x *HeroWorkingStatusMsg) GetWorkingStatus() int32 {
	if x != nil {
		return x.WorkingStatus
	}
	return 0
}

func (x *HeroWorkingStatusMsg) GetParams() []int32 {
	if x != nil {
		return x.Params
	}
	return nil
}

//升级
type HeroUpdateLevel_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroTid  int32 `protobuf:"varint,1,opt,name=heroTid,proto3" json:"heroTid,omitempty"`
	NewLevel int32 `protobuf:"varint,2,opt,name=newLevel,proto3" json:"newLevel,omitempty"` //要升到的等级
}

func (x *HeroUpdateLevel_C) Reset() {
	*x = HeroUpdateLevel_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroUpdateLevel_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpdateLevel_C) ProtoMessage() {}

func (x *HeroUpdateLevel_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpdateLevel_C.ProtoReflect.Descriptor instead.
func (*HeroUpdateLevel_C) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{5}
}

func (x *HeroUpdateLevel_C) GetHeroTid() int32 {
	if x != nil {
		return x.HeroTid
	}
	return 0
}

func (x *HeroUpdateLevel_C) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

type HeroUpdateLevel_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32        `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Hero   *HeroInfoMsg `protobuf:"bytes,2,opt,name=hero,proto3" json:"hero,omitempty"`
}

func (x *HeroUpdateLevel_S) Reset() {
	*x = HeroUpdateLevel_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroUpdateLevel_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpdateLevel_S) ProtoMessage() {}

func (x *HeroUpdateLevel_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpdateLevel_S.ProtoReflect.Descriptor instead.
func (*HeroUpdateLevel_S) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{6}
}

func (x *HeroUpdateLevel_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *HeroUpdateLevel_S) GetHero() *HeroInfoMsg {
	if x != nil {
		return x.Hero
	}
	return nil
}

//升级技能
type HeroUpdateSkillLevel_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroTid       int32 `protobuf:"varint,1,opt,name=heroTid,proto3" json:"heroTid,omitempty"`
	NewSkillLevel int32 `protobuf:"varint,2,opt,name=newSkillLevel,proto3" json:"newSkillLevel,omitempty"` //要升到的等级
}

func (x *HeroUpdateSkillLevel_C) Reset() {
	*x = HeroUpdateSkillLevel_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroUpdateSkillLevel_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpdateSkillLevel_C) ProtoMessage() {}

func (x *HeroUpdateSkillLevel_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpdateSkillLevel_C.ProtoReflect.Descriptor instead.
func (*HeroUpdateSkillLevel_C) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{7}
}

func (x *HeroUpdateSkillLevel_C) GetHeroTid() int32 {
	if x != nil {
		return x.HeroTid
	}
	return 0
}

func (x *HeroUpdateSkillLevel_C) GetNewSkillLevel() int32 {
	if x != nil {
		return x.NewSkillLevel
	}
	return 0
}

type HeroUpdateSkillLevel_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32        `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Hero   *HeroInfoMsg `protobuf:"bytes,2,opt,name=hero,proto3" json:"hero,omitempty"`
}

func (x *HeroUpdateSkillLevel_S) Reset() {
	*x = HeroUpdateSkillLevel_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroUpdateSkillLevel_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpdateSkillLevel_S) ProtoMessage() {}

func (x *HeroUpdateSkillLevel_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpdateSkillLevel_S.ProtoReflect.Descriptor instead.
func (*HeroUpdateSkillLevel_S) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{8}
}

func (x *HeroUpdateSkillLevel_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *HeroUpdateSkillLevel_S) GetHero() *HeroInfoMsg {
	if x != nil {
		return x.Hero
	}
	return nil
}

//升星
type HeroUpdateStar_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeroTid int32 `protobuf:"varint,1,opt,name=heroTid,proto3" json:"heroTid,omitempty"`
}

func (x *HeroUpdateStar_C) Reset() {
	*x = HeroUpdateStar_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroUpdateStar_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpdateStar_C) ProtoMessage() {}

func (x *HeroUpdateStar_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpdateStar_C.ProtoReflect.Descriptor instead.
func (*HeroUpdateStar_C) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{9}
}

func (x *HeroUpdateStar_C) GetHeroTid() int32 {
	if x != nil {
		return x.HeroTid
	}
	return 0
}

type HeroUpdateStar_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32        `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Hero   *HeroInfoMsg `protobuf:"bytes,2,opt,name=hero,proto3" json:"hero,omitempty"`
}

func (x *HeroUpdateStar_S) Reset() {
	*x = HeroUpdateStar_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroUpdateStar_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroUpdateStar_S) ProtoMessage() {}

func (x *HeroUpdateStar_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroUpdateStar_S.ProtoReflect.Descriptor instead.
func (*HeroUpdateStar_S) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{10}
}

func (x *HeroUpdateStar_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *HeroUpdateStar_S) GetHero() *HeroInfoMsg {
	if x != nil {
		return x.Hero
	}
	return nil
}

// 工作状态改变
type HeroWorkingStatusChange_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result        int32                 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	HeroTid       int32                 `protobuf:"varint,2,opt,name=heroTid,proto3" json:"heroTid,omitempty"`
	WorkingStatus *HeroWorkingStatusMsg `protobuf:"bytes,3,opt,name=workingStatus,proto3" json:"workingStatus,omitempty"`
}

func (x *HeroWorkingStatusChange_S) Reset() {
	*x = HeroWorkingStatusChange_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_hero_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeroWorkingStatusChange_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroWorkingStatusChange_S) ProtoMessage() {}

func (x *HeroWorkingStatusChange_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_hero_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroWorkingStatusChange_S.ProtoReflect.Descriptor instead.
func (*HeroWorkingStatusChange_S) Descriptor() ([]byte, []int) {
	return file_msg_hero_proto_rawDescGZIP(), []int{11}
}

func (x *HeroWorkingStatusChange_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *HeroWorkingStatusChange_S) GetHeroTid() int32 {
	if x != nil {
		return x.HeroTid
	}
	return 0
}

func (x *HeroWorkingStatusChange_S) GetWorkingStatus() *HeroWorkingStatusMsg {
	if x != nil {
		return x.WorkingStatus
	}
	return nil
}

var File_msg_hero_proto protoreflect.FileDescriptor

var file_msg_hero_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x73, 0x67, 0x2f, 0x68, 0x65, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x0c, 0x0a, 0x0a, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66,
	0x6f, 0x5f, 0x43, 0x22, 0x4c, 0x0a, 0x0a, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x5f,
	0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a, 0x05, 0x68, 0x65, 0x72,
	0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x48,
	0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x05, 0x68, 0x65, 0x72, 0x6f,
	0x73, 0x22, 0x52, 0x0a, 0x10, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x26, 0x0a,
	0x05, 0x68, 0x65, 0x72, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x05,
	0x68, 0x65, 0x72, 0x6f, 0x73, 0x22, 0xd1, 0x02, 0x0a, 0x0b, 0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e,
	0x66, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x72, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x74, 0x61, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x6b, 0x69, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x73, 0x6b, 0x69, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x34, 0x0a, 0x06, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x48, 0x65, 0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x73, 0x67, 0x2e, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x65, 0x71, 0x75, 0x69, 0x70, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x61, 0x73, 0x68, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x66, 0x61, 0x73, 0x68, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3f, 0x0a,
	0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x48, 0x65, 0x72, 0x6f, 0x57,
	0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73, 0x67, 0x52,
	0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x39,
	0x0a, 0x0b, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x54, 0x0a, 0x14, 0x48, 0x65, 0x72,
	0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73,
	0x67, 0x12, 0x24, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e,
	0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22,
	0x49, 0x0a, 0x11, 0x48, 0x65, 0x72, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x5f, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x65, 0x77, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x6e, 0x65, 0x77, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x51, 0x0a, 0x11, 0x48, 0x65,
	0x72, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x53, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x72, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x48, 0x65, 0x72, 0x6f,
	0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x68, 0x65, 0x72, 0x6f, 0x22, 0x58, 0x0a,
	0x16, 0x48, 0x65, 0x72, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69,
	0x64, 0x12, 0x24, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x56, 0x0a, 0x16, 0x48, 0x65, 0x72, 0x6f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x5f,
	0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x72,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x48, 0x65,
	0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x68, 0x65, 0x72, 0x6f, 0x22,
	0x2c, 0x0a, 0x10, 0x48, 0x65, 0x72, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61,
	0x72, 0x5f, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x22, 0x50, 0x0a,
	0x10, 0x48, 0x65, 0x72, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x61, 0x72, 0x5f,
	0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x04, 0x68, 0x65, 0x72,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x48, 0x65,
	0x72, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x73, 0x67, 0x52, 0x04, 0x68, 0x65, 0x72, 0x6f, 0x22,
	0x8e, 0x01, 0x0a, 0x19, 0x48, 0x65, 0x72, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x53, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x12,
	0x3f, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x48, 0x65, 0x72,
	0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4d, 0x73,
	0x67, 0x52, 0x0d, 0x77, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2a, 0x61, 0x0a, 0x11, 0x48, 0x65, 0x72, 0x6f, 0x57, 0x6f, 0x72, 0x6b, 0x69, 0x6e, 0x67, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x0a, 0x11, 0x48, 0x45, 0x52, 0x4f, 0x5f, 0x57, 0x4f,
	0x52, 0x4b, 0x49, 0x4e, 0x47, 0x5f, 0x49, 0x44, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16,
	0x48, 0x45, 0x52, 0x4f, 0x5f, 0x57, 0x4f, 0x52, 0x4b, 0x49, 0x4e, 0x47, 0x5f, 0x4d, 0x41, 0x4b,
	0x45, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x48, 0x45, 0x52, 0x4f,
	0x5f, 0x57, 0x4f, 0x52, 0x4b, 0x49, 0x4e, 0x47, 0x5f, 0x4f, 0x42, 0x53, 0x54, 0x41, 0x43, 0x4c,
	0x45, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_hero_proto_rawDescOnce sync.Once
	file_msg_hero_proto_rawDescData = file_msg_hero_proto_rawDesc
)

func file_msg_hero_proto_rawDescGZIP() []byte {
	file_msg_hero_proto_rawDescOnce.Do(func() {
		file_msg_hero_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_hero_proto_rawDescData)
	})
	return file_msg_hero_proto_rawDescData
}

var file_msg_hero_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_hero_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_msg_hero_proto_goTypes = []interface{}{
	(HeroWorkingStatus)(0),            // 0: msg.HeroWorkingStatus
	(*HeroInfo_C)(nil),                // 1: msg.HeroInfo_C
	(*HeroInfo_S)(nil),                // 2: msg.HeroInfo_S
	(*HeroInfoChange_S)(nil),          // 3: msg.HeroInfoChange_S
	(*HeroInfoMsg)(nil),               // 4: msg.HeroInfoMsg
	(*HeroWorkingStatusMsg)(nil),      // 5: msg.HeroWorkingStatusMsg
	(*HeroUpdateLevel_C)(nil),         // 6: msg.HeroUpdateLevel_C
	(*HeroUpdateLevel_S)(nil),         // 7: msg.HeroUpdateLevel_S
	(*HeroUpdateSkillLevel_C)(nil),    // 8: msg.HeroUpdateSkillLevel_C
	(*HeroUpdateSkillLevel_S)(nil),    // 9: msg.HeroUpdateSkillLevel_S
	(*HeroUpdateStar_C)(nil),          // 10: msg.HeroUpdateStar_C
	(*HeroUpdateStar_S)(nil),          // 11: msg.HeroUpdateStar_S
	(*HeroWorkingStatusChange_S)(nil), // 12: msg.HeroWorkingStatusChange_S
	nil,                               // 13: msg.HeroInfoMsg.EquipsEntry
}
var file_msg_hero_proto_depIdxs = []int32{
	4,  // 0: msg.HeroInfo_S.heros:type_name -> msg.HeroInfoMsg
	4,  // 1: msg.HeroInfoChange_S.heros:type_name -> msg.HeroInfoMsg
	13, // 2: msg.HeroInfoMsg.equips:type_name -> msg.HeroInfoMsg.EquipsEntry
	5,  // 3: msg.HeroInfoMsg.workingStatus:type_name -> msg.HeroWorkingStatusMsg
	4,  // 4: msg.HeroUpdateLevel_S.hero:type_name -> msg.HeroInfoMsg
	4,  // 5: msg.HeroUpdateSkillLevel_S.hero:type_name -> msg.HeroInfoMsg
	4,  // 6: msg.HeroUpdateStar_S.hero:type_name -> msg.HeroInfoMsg
	5,  // 7: msg.HeroWorkingStatusChange_S.workingStatus:type_name -> msg.HeroWorkingStatusMsg
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_msg_hero_proto_init() }
func file_msg_hero_proto_init() {
	if File_msg_hero_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_hero_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroInfo_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroInfoChange_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroInfoMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroWorkingStatusMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroUpdateLevel_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroUpdateLevel_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroUpdateSkillLevel_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroUpdateSkillLevel_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroUpdateStar_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroUpdateStar_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_hero_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeroWorkingStatusChange_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_hero_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_hero_proto_goTypes,
		DependencyIndexes: file_msg_hero_proto_depIdxs,
		EnumInfos:         file_msg_hero_proto_enumTypes,
		MessageInfos:      file_msg_hero_proto_msgTypes,
	}.Build()
	File_msg_hero_proto = out.File
	file_msg_hero_proto_rawDesc = nil
	file_msg_hero_proto_goTypes = nil
	file_msg_hero_proto_depIdxs = nil
}
