// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msg/map.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//地块组状态
type TileGroupState int32

const (
	TileGroupState_None      TileGroupState = 0 //
	TileGroupState_Unlocking TileGroupState = 1 //解锁中
	TileGroupState_Unlock    TileGroupState = 2 //已解锁
)

// Enum value maps for TileGroupState.
var (
	TileGroupState_name = map[int32]string{
		0: "None",
		1: "Unlocking",
		2: "Unlock",
	}
	TileGroupState_value = map[string]int32{
		"None":      0,
		"Unlocking": 1,
		"Unlock":    2,
	}
)

func (x TileGroupState) Enum() *TileGroupState {
	p := new(TileGroupState)
	*p = x
	return p
}

func (x TileGroupState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TileGroupState) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_map_proto_enumTypes[0].Descriptor()
}

func (TileGroupState) Type() protoreflect.EnumType {
	return &file_msg_map_proto_enumTypes[0]
}

func (x TileGroupState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TileGroupState.Descriptor instead.
func (TileGroupState) EnumDescriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{0}
}

type MapInfo_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
}

func (x *MapInfo_C) Reset() {
	*x = MapInfo_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapInfo_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInfo_C) ProtoMessage() {}

func (x *MapInfo_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInfo_C.ProtoReflect.Descriptor instead.
func (*MapInfo_C) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{0}
}

func (x *MapInfo_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

//地图信息
type MapInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32        `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Map    *MapInfoData `protobuf:"bytes,2,opt,name=map,proto3" json:"map,omitempty"`
}

func (x *MapInfo_S) Reset() {
	*x = MapInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInfo_S) ProtoMessage() {}

func (x *MapInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInfo_S.ProtoReflect.Descriptor instead.
func (*MapInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{1}
}

func (x *MapInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *MapInfo_S) GetMap() *MapInfoData {
	if x != nil {
		return x.Map
	}
	return nil
}

//场景信息
type MapInfoData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId      int32               `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Tiles      []*MapTileInfo      `protobuf:"bytes,2,rep,name=tiles,proto3" json:"tiles,omitempty"`
	TileGroups []*MapTileGroupInfo `protobuf:"bytes,3,rep,name=tileGroups,proto3" json:"tileGroups,omitempty"`
	Elements   []*MapElementInfo   `protobuf:"bytes,4,rep,name=elements,proto3" json:"elements,omitempty"` //包括已解锁的功能建筑
	SkinInfos  []*ElementSkinInfo  `protobuf:"bytes,5,rep,name=skinInfos,proto3" json:"skinInfos,omitempty"`
}

func (x *MapInfoData) Reset() {
	*x = MapInfoData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapInfoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapInfoData) ProtoMessage() {}

func (x *MapInfoData) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapInfoData.ProtoReflect.Descriptor instead.
func (*MapInfoData) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{2}
}

func (x *MapInfoData) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapInfoData) GetTiles() []*MapTileInfo {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *MapInfoData) GetTileGroups() []*MapTileGroupInfo {
	if x != nil {
		return x.TileGroups
	}
	return nil
}

func (x *MapInfoData) GetElements() []*MapElementInfo {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *MapInfoData) GetSkinInfos() []*ElementSkinInfo {
	if x != nil {
		return x.SkinInfos
	}
	return nil
}

//地块信息
type MapTileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos  int32 `protobuf:"varint,1,opt,name=pos,proto3" json:"pos,omitempty"`
	Skin int32 `protobuf:"varint,2,opt,name=skin,proto3" json:"skin,omitempty"`
}

func (x *MapTileInfo) Reset() {
	*x = MapTileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTileInfo) ProtoMessage() {}

func (x *MapTileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTileInfo.ProtoReflect.Descriptor instead.
func (*MapTileInfo) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{3}
}

func (x *MapTileInfo) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *MapTileInfo) GetSkin() int32 {
	if x != nil {
		return x.Skin
	}
	return 0
}

type ElementSkinInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid  int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Skin int32 `protobuf:"varint,2,opt,name=skin,proto3" json:"skin,omitempty"`
}

func (x *ElementSkinInfo) Reset() {
	*x = ElementSkinInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementSkinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementSkinInfo) ProtoMessage() {}

func (x *ElementSkinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementSkinInfo.ProtoReflect.Descriptor instead.
func (*ElementSkinInfo) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{4}
}

func (x *ElementSkinInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementSkinInfo) GetSkin() int32 {
	if x != nil {
		return x.Skin
	}
	return 0
}

//地块组状态信息
type MapTileGroupInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupId int32          `protobuf:"varint,1,opt,name=groupId,proto3" json:"groupId,omitempty"`
	State   TileGroupState `protobuf:"varint,2,opt,name=state,proto3,enum=msg.TileGroupState" json:"state,omitempty"`
	// Deprecated: Do not use.
	Time   int32   `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"` //开始解锁时间
	CdInfo *CDInfo `protobuf:"bytes,4,opt,name=cdInfo,proto3" json:"cdInfo,omitempty"`
}

func (x *MapTileGroupInfo) Reset() {
	*x = MapTileGroupInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTileGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTileGroupInfo) ProtoMessage() {}

func (x *MapTileGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTileGroupInfo.ProtoReflect.Descriptor instead.
func (*MapTileGroupInfo) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{5}
}

func (x *MapTileGroupInfo) GetGroupId() int32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MapTileGroupInfo) GetState() TileGroupState {
	if x != nil {
		return x.State
	}
	return TileGroupState_None
}

// Deprecated: Do not use.
func (x *MapTileGroupInfo) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *MapTileGroupInfo) GetCdInfo() *CDInfo {
	if x != nil {
		return x.CdInfo
	}
	return nil
}

//场景地上物信息
type MapElementInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid  int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Pos  int32 `protobuf:"varint,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Skin int32 `protobuf:"varint,3,opt,name=skin,proto3" json:"skin,omitempty"`
	Dir  int32 `protobuf:"varint,4,opt,name=dir,proto3" json:"dir,omitempty"` //方向
	Tid  int32 `protobuf:"varint,5,opt,name=tid,proto3" json:"tid,omitempty"`
}

func (x *MapElementInfo) Reset() {
	*x = MapElementInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapElementInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapElementInfo) ProtoMessage() {}

func (x *MapElementInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapElementInfo.ProtoReflect.Descriptor instead.
func (*MapElementInfo) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{6}
}

func (x *MapElementInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *MapElementInfo) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *MapElementInfo) GetSkin() int32 {
	if x != nil {
		return x.Skin
	}
	return 0
}

func (x *MapElementInfo) GetDir() int32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

func (x *MapElementInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

//地块组解锁请求
type MapTileGroupUnlock_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TileGroupId int32 `protobuf:"varint,1,opt,name=tileGroupId,proto3" json:"tileGroupId,omitempty"` //可以索引到所在的地图id
}

func (x *MapTileGroupUnlock_C) Reset() {
	*x = MapTileGroupUnlock_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTileGroupUnlock_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTileGroupUnlock_C) ProtoMessage() {}

func (x *MapTileGroupUnlock_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTileGroupUnlock_C.ProtoReflect.Descriptor instead.
func (*MapTileGroupUnlock_C) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{7}
}

func (x *MapTileGroupUnlock_C) GetTileGroupId() int32 {
	if x != nil {
		return x.TileGroupId
	}
	return 0
}

//地块组解锁响应
type MapTileGroupUnlock_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	TileGroupId int32 `protobuf:"varint,2,opt,name=tileGroupId,proto3" json:"tileGroupId,omitempty"`
	StartTime   int32 `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"` //解锁开始时间
}

func (x *MapTileGroupUnlock_S) Reset() {
	*x = MapTileGroupUnlock_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTileGroupUnlock_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTileGroupUnlock_S) ProtoMessage() {}

func (x *MapTileGroupUnlock_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTileGroupUnlock_S.ProtoReflect.Descriptor instead.
func (*MapTileGroupUnlock_S) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{8}
}

func (x *MapTileGroupUnlock_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *MapTileGroupUnlock_S) GetTileGroupId() int32 {
	if x != nil {
		return x.TileGroupId
	}
	return 0
}

func (x *MapTileGroupUnlock_S) GetStartTime() int32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

// 完成解锁操作
type MapTileGroupFinishUnlock_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TileGroupId int32 `protobuf:"varint,1,opt,name=tileGroupId,proto3" json:"tileGroupId,omitempty"` //可以索引到所在的地图id
}

func (x *MapTileGroupFinishUnlock_C) Reset() {
	*x = MapTileGroupFinishUnlock_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTileGroupFinishUnlock_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTileGroupFinishUnlock_C) ProtoMessage() {}

func (x *MapTileGroupFinishUnlock_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTileGroupFinishUnlock_C.ProtoReflect.Descriptor instead.
func (*MapTileGroupFinishUnlock_C) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{9}
}

func (x *MapTileGroupFinishUnlock_C) GetTileGroupId() int32 {
	if x != nil {
		return x.TileGroupId
	}
	return 0
}

type MapTileGroupFinishUnlock_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result      int32             `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	TileGroupId int32             `protobuf:"varint,2,opt,name=tileGroupId,proto3" json:"tileGroupId,omitempty"` //可以索引到所在的地图id
	Elements    []*MapElementInfo `protobuf:"bytes,3,rep,name=elements,proto3" json:"elements,omitempty"`        //包括已解锁的功能建筑
}

func (x *MapTileGroupFinishUnlock_S) Reset() {
	*x = MapTileGroupFinishUnlock_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapTileGroupFinishUnlock_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapTileGroupFinishUnlock_S) ProtoMessage() {}

func (x *MapTileGroupFinishUnlock_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapTileGroupFinishUnlock_S.ProtoReflect.Descriptor instead.
func (*MapTileGroupFinishUnlock_S) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{10}
}

func (x *MapTileGroupFinishUnlock_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *MapTileGroupFinishUnlock_S) GetTileGroupId() int32 {
	if x != nil {
		return x.TileGroupId
	}
	return 0
}

func (x *MapTileGroupFinishUnlock_S) GetElements() []*MapElementInfo {
	if x != nil {
		return x.Elements
	}
	return nil
}

//地编地上物变更请求
type MapElementChange_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId  int32                    `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Buys   []*ElementChangeBuyInfo  `protobuf:"bytes,2,rep,name=buys,proto3" json:"buys,omitempty"`
	InBags []int32                  `protobuf:"varint,3,rep,packed,name=inBags,proto3" json:"inBags,omitempty"`
	Sells  []*ElementChangeSellInfo `protobuf:"bytes,4,rep,name=sells,proto3" json:"sells,omitempty"`
	Moves  []*ElementChangeMoveInfo `protobuf:"bytes,5,rep,name=moves,proto3" json:"moves,omitempty"`
	Tiles  []*ElementChangeTileInfo `protobuf:"bytes,6,rep,name=tiles,proto3" json:"tiles,omitempty"`
}

func (x *MapElementChange_C) Reset() {
	*x = MapElementChange_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapElementChange_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapElementChange_C) ProtoMessage() {}

func (x *MapElementChange_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapElementChange_C.ProtoReflect.Descriptor instead.
func (*MapElementChange_C) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{11}
}

func (x *MapElementChange_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapElementChange_C) GetBuys() []*ElementChangeBuyInfo {
	if x != nil {
		return x.Buys
	}
	return nil
}

func (x *MapElementChange_C) GetInBags() []int32 {
	if x != nil {
		return x.InBags
	}
	return nil
}

func (x *MapElementChange_C) GetSells() []*ElementChangeSellInfo {
	if x != nil {
		return x.Sells
	}
	return nil
}

func (x *MapElementChange_C) GetMoves() []*ElementChangeMoveInfo {
	if x != nil {
		return x.Moves
	}
	return nil
}

func (x *MapElementChange_C) GetTiles() []*ElementChangeTileInfo {
	if x != nil {
		return x.Tiles
	}
	return nil
}

type ElementChangeBuyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Tid int32 `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
}

func (x *ElementChangeBuyInfo) Reset() {
	*x = ElementChangeBuyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementChangeBuyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementChangeBuyInfo) ProtoMessage() {}

func (x *ElementChangeBuyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementChangeBuyInfo.ProtoReflect.Descriptor instead.
func (*ElementChangeBuyInfo) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{12}
}

func (x *ElementChangeBuyInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementChangeBuyInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

type ElementChangeMoveInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Tid int32 `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	Pos int32 `protobuf:"varint,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Dir int32 `protobuf:"varint,4,opt,name=dir,proto3" json:"dir,omitempty"`
}

func (x *ElementChangeMoveInfo) Reset() {
	*x = ElementChangeMoveInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementChangeMoveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementChangeMoveInfo) ProtoMessage() {}

func (x *ElementChangeMoveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementChangeMoveInfo.ProtoReflect.Descriptor instead.
func (*ElementChangeMoveInfo) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{13}
}

func (x *ElementChangeMoveInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementChangeMoveInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ElementChangeMoveInfo) GetPos() int32 {
	if x != nil {
		return x.Pos
	}
	return 0
}

func (x *ElementChangeMoveInfo) GetDir() int32 {
	if x != nil {
		return x.Dir
	}
	return 0
}

type ElementChangeSellInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Tid int32 `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	Num int32 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *ElementChangeSellInfo) Reset() {
	*x = ElementChangeSellInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementChangeSellInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementChangeSellInfo) ProtoMessage() {}

func (x *ElementChangeSellInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementChangeSellInfo.ProtoReflect.Descriptor instead.
func (*ElementChangeSellInfo) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{14}
}

func (x *ElementChangeSellInfo) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ElementChangeSellInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ElementChangeSellInfo) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ElementChangeTileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tid    int32   `protobuf:"varint,1,opt,name=tid,proto3" json:"tid,omitempty"`
	TileId []int32 `protobuf:"varint,2,rep,packed,name=tileId,proto3" json:"tileId,omitempty"` //坐标
}

func (x *ElementChangeTileInfo) Reset() {
	*x = ElementChangeTileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElementChangeTileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementChangeTileInfo) ProtoMessage() {}

func (x *ElementChangeTileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementChangeTileInfo.ProtoReflect.Descriptor instead.
func (*ElementChangeTileInfo) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{15}
}

func (x *ElementChangeTileInfo) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *ElementChangeTileInfo) GetTileId() []int32 {
	if x != nil {
		return x.TileId
	}
	return nil
}

//地编地上物变更响应
type MapElementChange_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MapId  int32                  `protobuf:"varint,2,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Sids   []*MapElementChangeSid `protobuf:"bytes,3,rep,name=sids,proto3" json:"sids,omitempty"`
}

func (x *MapElementChange_S) Reset() {
	*x = MapElementChange_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapElementChange_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapElementChange_S) ProtoMessage() {}

func (x *MapElementChange_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapElementChange_S.ProtoReflect.Descriptor instead.
func (*MapElementChange_S) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{16}
}

func (x *MapElementChange_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *MapElementChange_S) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *MapElementChange_S) GetSids() []*MapElementChangeSid {
	if x != nil {
		return x.Sids
	}
	return nil
}

type MapElementChangeSid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sid    int32 `protobuf:"varint,1,opt,name=sid,proto3" json:"sid,omitempty"`
	NewSid int32 `protobuf:"varint,2,opt,name=newSid,proto3" json:"newSid,omitempty"`
}

func (x *MapElementChangeSid) Reset() {
	*x = MapElementChangeSid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapElementChangeSid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapElementChangeSid) ProtoMessage() {}

func (x *MapElementChangeSid) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapElementChangeSid.ProtoReflect.Descriptor instead.
func (*MapElementChangeSid) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{17}
}

func (x *MapElementChangeSid) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *MapElementChangeSid) GetNewSid() int32 {
	if x != nil {
		return x.NewSid
	}
	return 0
}

type ObstacleClear_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId   int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Sid     int32 `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	HeroTid int32 `protobuf:"varint,3,opt,name=heroTid,proto3" json:"heroTid,omitempty"`
}

func (x *ObstacleClear_C) Reset() {
	*x = ObstacleClear_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObstacleClear_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObstacleClear_C) ProtoMessage() {}

func (x *ObstacleClear_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObstacleClear_C.ProtoReflect.Descriptor instead.
func (*ObstacleClear_C) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{18}
}

func (x *ObstacleClear_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ObstacleClear_C) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ObstacleClear_C) GetHeroTid() int32 {
	if x != nil {
		return x.HeroTid
	}
	return 0
}

type ObstacleClear_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       int32         `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Sid          int32         `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
	ObstacleInfo *ObstacleInfo `protobuf:"bytes,3,opt,name=obstacleInfo,proto3" json:"obstacleInfo,omitempty"`
}

func (x *ObstacleClear_S) Reset() {
	*x = ObstacleClear_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObstacleClear_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObstacleClear_S) ProtoMessage() {}

func (x *ObstacleClear_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObstacleClear_S.ProtoReflect.Descriptor instead.
func (*ObstacleClear_S) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{19}
}

func (x *ObstacleClear_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ObstacleClear_S) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

func (x *ObstacleClear_S) GetObstacleInfo() *ObstacleInfo {
	if x != nil {
		return x.ObstacleInfo
	}
	return nil
}

type ObstacleClearFinish_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Sid   int32 `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *ObstacleClearFinish_C) Reset() {
	*x = ObstacleClearFinish_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObstacleClearFinish_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObstacleClearFinish_C) ProtoMessage() {}

func (x *ObstacleClearFinish_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObstacleClearFinish_C.ProtoReflect.Descriptor instead.
func (*ObstacleClearFinish_C) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{20}
}

func (x *ObstacleClearFinish_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *ObstacleClearFinish_C) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

type ObstacleClearFinish_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Sid    int32 `protobuf:"varint,2,opt,name=sid,proto3" json:"sid,omitempty"`
}

func (x *ObstacleClearFinish_S) Reset() {
	*x = ObstacleClearFinish_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObstacleClearFinish_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObstacleClearFinish_S) ProtoMessage() {}

func (x *ObstacleClearFinish_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObstacleClearFinish_S.ProtoReflect.Descriptor instead.
func (*ObstacleClearFinish_S) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{21}
}

func (x *ObstacleClearFinish_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ObstacleClearFinish_S) GetSid() int32 {
	if x != nil {
		return x.Sid
	}
	return 0
}

//皮肤编辑
type SkinEdit_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32   `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Sid   []int32 `protobuf:"varint,2,rep,packed,name=sid,proto3" json:"sid,omitempty"`
	Skin  int32   `protobuf:"varint,3,opt,name=skin,proto3" json:"skin,omitempty"`
}

func (x *SkinEdit_C) Reset() {
	*x = SkinEdit_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkinEdit_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinEdit_C) ProtoMessage() {}

func (x *SkinEdit_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinEdit_C.ProtoReflect.Descriptor instead.
func (*SkinEdit_C) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{22}
}

func (x *SkinEdit_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *SkinEdit_C) GetSid() []int32 {
	if x != nil {
		return x.Sid
	}
	return nil
}

func (x *SkinEdit_C) GetSkin() int32 {
	if x != nil {
		return x.Skin
	}
	return 0
}

//皮肤编辑
type SkinEdit_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Sid    []int32 `protobuf:"varint,2,rep,packed,name=sid,proto3" json:"sid,omitempty"`
	Skin   int32   `protobuf:"varint,3,opt,name=skin,proto3" json:"skin,omitempty"`
}

func (x *SkinEdit_S) Reset() {
	*x = SkinEdit_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkinEdit_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinEdit_S) ProtoMessage() {}

func (x *SkinEdit_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinEdit_S.ProtoReflect.Descriptor instead.
func (*SkinEdit_S) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{23}
}

func (x *SkinEdit_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SkinEdit_S) GetSid() []int32 {
	if x != nil {
		return x.Sid
	}
	return nil
}

func (x *SkinEdit_S) GetSkin() int32 {
	if x != nil {
		return x.Skin
	}
	return 0
}

type SkinBuy_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapId int32 `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	Skin  int32 `protobuf:"varint,2,opt,name=skin,proto3" json:"skin,omitempty"`
}

func (x *SkinBuy_C) Reset() {
	*x = SkinBuy_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkinBuy_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinBuy_C) ProtoMessage() {}

func (x *SkinBuy_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinBuy_C.ProtoReflect.Descriptor instead.
func (*SkinBuy_C) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{24}
}

func (x *SkinBuy_C) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *SkinBuy_C) GetSkin() int32 {
	if x != nil {
		return x.Skin
	}
	return 0
}

type SkinBuy_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Skin   int32 `protobuf:"varint,2,opt,name=skin,proto3" json:"skin,omitempty"`
}

func (x *SkinBuy_S) Reset() {
	*x = SkinBuy_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkinBuy_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinBuy_S) ProtoMessage() {}

func (x *SkinBuy_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinBuy_S.ProtoReflect.Descriptor instead.
func (*SkinBuy_S) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{25}
}

func (x *SkinBuy_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SkinBuy_S) GetSkin() int32 {
	if x != nil {
		return x.Skin
	}
	return 0
}

// 皮肤新增
type SkinChange_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Skin   []int32 `protobuf:"varint,2,rep,packed,name=skin,proto3" json:"skin,omitempty"`
}

func (x *SkinChange_S) Reset() {
	*x = SkinChange_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_map_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SkinChange_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinChange_S) ProtoMessage() {}

func (x *SkinChange_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_map_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinChange_S.ProtoReflect.Descriptor instead.
func (*SkinChange_S) Descriptor() ([]byte, []int) {
	return file_msg_map_proto_rawDescGZIP(), []int{26}
}

func (x *SkinChange_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SkinChange_S) GetSkin() []int32 {
	if x != nil {
		return x.Skin
	}
	return nil
}

var File_msg_map_proto protoreflect.FileDescriptor

var file_msg_map_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6d, 0x73, 0x67, 0x1a, 0x10, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x6d, 0x73, 0x67, 0x2f, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a,
	0x09, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61,
	0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64,
	0x22, 0x47, 0x0a, 0x09, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x03, 0x6d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x03, 0x6d, 0x61, 0x70, 0x22, 0xe7, 0x01, 0x0a, 0x0b, 0x4d, 0x61,
	0x70, 0x49, 0x6e, 0x66, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12,
	0x26, 0x0a, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x70, 0x54, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x35, 0x0a, 0x0a, 0x74, 0x69, 0x6c, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x4d, 0x61, 0x70, 0x54, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0a, 0x74, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x2f,
	0x0a, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12,
	0x32, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x53, 0x6b, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x73, 0x6b, 0x69, 0x6e, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x22, 0x33, 0x0a, 0x0b, 0x4d, 0x61, 0x70, 0x54, 0x69, 0x6c, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x70, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x22, 0x37, 0x0a, 0x0f, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x6b, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6b, 0x69,
	0x6e, 0x22, 0x94, 0x01, 0x0a, 0x10, 0x4d, 0x61, 0x70, 0x54, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x12, 0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x54, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x42, 0x02, 0x18, 0x01, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x63, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x44, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x06, 0x63, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x6c, 0x0a, 0x0e, 0x4d, 0x61, 0x70, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x70, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6b,
	0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x64, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x14, 0x4d, 0x61, 0x70, 0x54, 0x69, 0x6c,
	0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x43, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x22, 0x6e, 0x0a, 0x14, 0x4d, 0x61, 0x70, 0x54, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x3e, 0x0a, 0x1a, 0x4d, 0x61, 0x70, 0x54, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x43, 0x12, 0x20,
	0x0a, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64,
	0x22, 0x87, 0x01, 0x0a, 0x1a, 0x4d, 0x61, 0x70, 0x54, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x53, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x69, 0x6c, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x69,
	0x6c, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x08, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x4d, 0x61, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x08, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x87, 0x02, 0x0a, 0x12, 0x4d,
	0x61, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f,
	0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x04, 0x62, 0x75, 0x79, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x75, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x62, 0x75, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x6e, 0x42, 0x61, 0x67, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x69, 0x6e, 0x42, 0x61, 0x67, 0x73, 0x12, 0x30,
	0x0a, 0x05, 0x73, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x53, 0x65, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x73, 0x65, 0x6c, 0x6c, 0x73,
	0x12, 0x30, 0x0a, 0x05, 0x6d, 0x6f, 0x76, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x6d, 0x6f, 0x76,
	0x65, 0x73, 0x12, 0x30, 0x0a, 0x05, 0x74, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x74,
	0x69, 0x6c, 0x65, 0x73, 0x22, 0x3a, 0x0a, 0x14, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x75, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64,
	0x22, 0x5f, 0x0a, 0x15, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12,
	0x10, 0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x64, 0x69,
	0x72, 0x22, 0x4d, 0x0a, 0x15, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x22, 0x41, 0x0a, 0x15, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x54, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x69, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x74, 0x69, 0x6c,
	0x65, 0x49, 0x64, 0x22, 0x70, 0x0a, 0x12, 0x4d, 0x61, 0x70, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x61, 0x70, 0x45,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x69, 0x64, 0x52,
	0x04, 0x73, 0x69, 0x64, 0x73, 0x22, 0x3f, 0x0a, 0x13, 0x4d, 0x61, 0x70, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6e, 0x65, 0x77, 0x53, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x6e, 0x65, 0x77, 0x53, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x0f, 0x4f, 0x62, 0x73, 0x74, 0x61, 0x63,
	0x6c, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x68, 0x65, 0x72, 0x6f, 0x54, 0x69, 0x64, 0x22, 0x72, 0x0a, 0x0f, 0x4f,
	0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x72, 0x5f, 0x53, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x35, 0x0a, 0x0c, 0x6f, 0x62, 0x73, 0x74,
	0x61, 0x63, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x0c, 0x6f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x3f, 0x0a, 0x15, 0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x43, 0x6c, 0x65, 0x61, 0x72,
	0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64,
	0x22, 0x41, 0x0a, 0x15, 0x4f, 0x62, 0x73, 0x74, 0x61, 0x63, 0x6c, 0x65, 0x43, 0x6c, 0x65, 0x61,
	0x72, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x73, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x0a, 0x53, 0x6b, 0x69, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x5f,
	0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x22, 0x4a, 0x0a,
	0x0a, 0x53, 0x6b, 0x69, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x69, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x03, 0x73, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x22, 0x35, 0x0a, 0x09, 0x53, 0x6b, 0x69,
	0x6e, 0x42, 0x75, 0x79, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x6b, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x6e,
	0x22, 0x37, 0x0a, 0x09, 0x53, 0x6b, 0x69, 0x6e, 0x42, 0x75, 0x79, 0x5f, 0x53, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x22, 0x3a, 0x0a, 0x0c, 0x53, 0x6b, 0x69,
	0x6e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x04, 0x73, 0x6b, 0x69, 0x6e, 0x2a, 0x35, 0x0a, 0x0e, 0x54, 0x69, 0x6c, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x69, 0x6e, 0x67, 0x10, 0x01,
	0x12, 0x0a, 0x0a, 0x06, 0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_map_proto_rawDescOnce sync.Once
	file_msg_map_proto_rawDescData = file_msg_map_proto_rawDesc
)

func file_msg_map_proto_rawDescGZIP() []byte {
	file_msg_map_proto_rawDescOnce.Do(func() {
		file_msg_map_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_map_proto_rawDescData)
	})
	return file_msg_map_proto_rawDescData
}

var file_msg_map_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_map_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_msg_map_proto_goTypes = []interface{}{
	(TileGroupState)(0),                // 0: msg.TileGroupState
	(*MapInfo_C)(nil),                  // 1: msg.MapInfo_C
	(*MapInfo_S)(nil),                  // 2: msg.MapInfo_S
	(*MapInfoData)(nil),                // 3: msg.MapInfoData
	(*MapTileInfo)(nil),                // 4: msg.MapTileInfo
	(*ElementSkinInfo)(nil),            // 5: msg.ElementSkinInfo
	(*MapTileGroupInfo)(nil),           // 6: msg.MapTileGroupInfo
	(*MapElementInfo)(nil),             // 7: msg.MapElementInfo
	(*MapTileGroupUnlock_C)(nil),       // 8: msg.MapTileGroupUnlock_C
	(*MapTileGroupUnlock_S)(nil),       // 9: msg.MapTileGroupUnlock_S
	(*MapTileGroupFinishUnlock_C)(nil), // 10: msg.MapTileGroupFinishUnlock_C
	(*MapTileGroupFinishUnlock_S)(nil), // 11: msg.MapTileGroupFinishUnlock_S
	(*MapElementChange_C)(nil),         // 12: msg.MapElementChange_C
	(*ElementChangeBuyInfo)(nil),       // 13: msg.ElementChangeBuyInfo
	(*ElementChangeMoveInfo)(nil),      // 14: msg.ElementChangeMoveInfo
	(*ElementChangeSellInfo)(nil),      // 15: msg.ElementChangeSellInfo
	(*ElementChangeTileInfo)(nil),      // 16: msg.ElementChangeTileInfo
	(*MapElementChange_S)(nil),         // 17: msg.MapElementChange_S
	(*MapElementChangeSid)(nil),        // 18: msg.MapElementChangeSid
	(*ObstacleClear_C)(nil),            // 19: msg.ObstacleClear_C
	(*ObstacleClear_S)(nil),            // 20: msg.ObstacleClear_S
	(*ObstacleClearFinish_C)(nil),      // 21: msg.ObstacleClearFinish_C
	(*ObstacleClearFinish_S)(nil),      // 22: msg.ObstacleClearFinish_S
	(*SkinEdit_C)(nil),                 // 23: msg.SkinEdit_C
	(*SkinEdit_S)(nil),                 // 24: msg.SkinEdit_S
	(*SkinBuy_C)(nil),                  // 25: msg.SkinBuy_C
	(*SkinBuy_S)(nil),                  // 26: msg.SkinBuy_S
	(*SkinChange_S)(nil),               // 27: msg.SkinChange_S
	(*CDInfo)(nil),                     // 28: msg.CDInfo
	(*ObstacleInfo)(nil),               // 29: msg.ObstacleInfo
}
var file_msg_map_proto_depIdxs = []int32{
	3,  // 0: msg.MapInfo_S.map:type_name -> msg.MapInfoData
	4,  // 1: msg.MapInfoData.tiles:type_name -> msg.MapTileInfo
	6,  // 2: msg.MapInfoData.tileGroups:type_name -> msg.MapTileGroupInfo
	7,  // 3: msg.MapInfoData.elements:type_name -> msg.MapElementInfo
	5,  // 4: msg.MapInfoData.skinInfos:type_name -> msg.ElementSkinInfo
	0,  // 5: msg.MapTileGroupInfo.state:type_name -> msg.TileGroupState
	28, // 6: msg.MapTileGroupInfo.cdInfo:type_name -> msg.CDInfo
	7,  // 7: msg.MapTileGroupFinishUnlock_S.elements:type_name -> msg.MapElementInfo
	13, // 8: msg.MapElementChange_C.buys:type_name -> msg.ElementChangeBuyInfo
	15, // 9: msg.MapElementChange_C.sells:type_name -> msg.ElementChangeSellInfo
	14, // 10: msg.MapElementChange_C.moves:type_name -> msg.ElementChangeMoveInfo
	16, // 11: msg.MapElementChange_C.tiles:type_name -> msg.ElementChangeTileInfo
	18, // 12: msg.MapElementChange_S.sids:type_name -> msg.MapElementChangeSid
	29, // 13: msg.ObstacleClear_S.obstacleInfo:type_name -> msg.ObstacleInfo
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_msg_map_proto_init() }
func file_msg_map_proto_init() {
	if File_msg_map_proto != nil {
		return
	}
	file_msg_common_proto_init()
	file_msg_elementinfo_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_map_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapInfo_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapInfoData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementSkinInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTileGroupInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapElementInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTileGroupUnlock_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTileGroupUnlock_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTileGroupFinishUnlock_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapTileGroupFinishUnlock_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapElementChange_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementChangeBuyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementChangeMoveInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementChangeSellInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ElementChangeTileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapElementChange_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapElementChangeSid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObstacleClear_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObstacleClear_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObstacleClearFinish_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObstacleClearFinish_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkinEdit_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkinEdit_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkinBuy_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkinBuy_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_map_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SkinChange_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_map_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_map_proto_goTypes,
		DependencyIndexes: file_msg_map_proto_depIdxs,
		EnumInfos:         file_msg_map_proto_enumTypes,
		MessageInfos:      file_msg_map_proto_msgTypes,
	}.Build()
	File_msg_map_proto = out.File
	file_msg_map_proto_rawDesc = nil
	file_msg_map_proto_goTypes = nil
	file_msg_map_proto_depIdxs = nil
}
