// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msg/module_number.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//计数器id
type ModuleType int32

const (
	ModuleType_M_None      ModuleType = 0 //
	ModuleType_M_wish_tree ModuleType = 1 //许愿树
	ModuleType_M_train     ModuleType = 2 //火车
)

// Enum value maps for ModuleType.
var (
	ModuleType_name = map[int32]string{
		0: "M_None",
		1: "M_wish_tree",
		2: "M_train",
	}
	ModuleType_value = map[string]int32{
		"M_None":      0,
		"M_wish_tree": 1,
		"M_train":     2,
	}
)

func (x ModuleType) Enum() *ModuleType {
	p := new(ModuleType)
	*p = x
	return p
}

func (x ModuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_module_number_proto_enumTypes[0].Descriptor()
}

func (ModuleType) Type() protoreflect.EnumType {
	return &file_msg_module_number_proto_enumTypes[0]
}

func (x ModuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleType.Descriptor instead.
func (ModuleType) EnumDescriptor() ([]byte, []int) {
	return file_msg_module_number_proto_rawDescGZIP(), []int{0}
}

//计数器
type ModuleNumberInfo_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ModuleNumberInfo_C) Reset() {
	*x = ModuleNumberInfo_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_module_number_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleNumberInfo_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleNumberInfo_C) ProtoMessage() {}

func (x *ModuleNumberInfo_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_module_number_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleNumberInfo_C.ProtoReflect.Descriptor instead.
func (*ModuleNumberInfo_C) Descriptor() ([]byte, []int) {
	return file_msg_module_number_proto_rawDescGZIP(), []int{0}
}

type ModuleNumberInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32           `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	DayNum map[int32]int32 `protobuf:"bytes,2,rep,name=dayNum,proto3" json:"dayNum,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //日刷新次数<id, 次数>
	AllNum map[int32]int32 `protobuf:"bytes,3,rep,name=allNum,proto3" json:"allNum,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //累计次数<id, 次数>
}

func (x *ModuleNumberInfo_S) Reset() {
	*x = ModuleNumberInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_module_number_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleNumberInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleNumberInfo_S) ProtoMessage() {}

func (x *ModuleNumberInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_module_number_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleNumberInfo_S.ProtoReflect.Descriptor instead.
func (*ModuleNumberInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_module_number_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleNumberInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ModuleNumberInfo_S) GetDayNum() map[int32]int32 {
	if x != nil {
		return x.DayNum
	}
	return nil
}

func (x *ModuleNumberInfo_S) GetAllNum() map[int32]int32 {
	if x != nil {
		return x.AllNum
	}
	return nil
}

//update信息， 最终值
type ModuleNumberChangeInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32           `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	DayNum map[int32]int32 `protobuf:"bytes,2,rep,name=dayNum,proto3" json:"dayNum,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //日刷新次数<id, 次数>
	AllNum map[int32]int32 `protobuf:"bytes,3,rep,name=allNum,proto3" json:"allNum,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //累计次数<id, 次数>
}

func (x *ModuleNumberChangeInfo_S) Reset() {
	*x = ModuleNumberChangeInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_module_number_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleNumberChangeInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleNumberChangeInfo_S) ProtoMessage() {}

func (x *ModuleNumberChangeInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_module_number_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleNumberChangeInfo_S.ProtoReflect.Descriptor instead.
func (*ModuleNumberChangeInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_module_number_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleNumberChangeInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ModuleNumberChangeInfo_S) GetDayNum() map[int32]int32 {
	if x != nil {
		return x.DayNum
	}
	return nil
}

func (x *ModuleNumberChangeInfo_S) GetAllNum() map[int32]int32 {
	if x != nil {
		return x.AllNum
	}
	return nil
}

var File_msg_module_number_proto protoreflect.FileDescriptor

var file_msg_module_number_proto_rawDesc = []byte{
	0x0a, 0x17, 0x6d, 0x73, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x14,
	0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x5f, 0x43, 0x22, 0x9c, 0x02, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x3b, 0x0a, 0x06, 0x64, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x2e, 0x44, 0x61, 0x79,
	0x4e, 0x75, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x64, 0x61, 0x79, 0x4e, 0x75, 0x6d,
	0x12, 0x3b, 0x0a, 0x06, 0x61, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x2e, 0x41, 0x6c, 0x6c, 0x4e, 0x75, 0x6d,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x61, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x1a, 0x39, 0x0a,
	0x0b, 0x44, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x39, 0x0a, 0x0b, 0x41, 0x6c, 0x6c, 0x4e,
	0x75, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0xae, 0x02, 0x0a, 0x18, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x41, 0x0a, 0x06, 0x64, 0x61, 0x79, 0x4e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x2e, 0x44, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x64, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x12, 0x41, 0x0a, 0x06, 0x61,
	0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x73,
	0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x2e, 0x41, 0x6c, 0x6c, 0x4e, 0x75,
	0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x61, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x1a, 0x39,
	0x0a, 0x0b, 0x44, 0x61, 0x79, 0x4e, 0x75, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x39, 0x0a, 0x0b, 0x41, 0x6c, 0x6c,
	0x4e, 0x75, 0x6d, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x2a, 0x36, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x4d, 0x5f, 0x77, 0x69, 0x73, 0x68, 0x5f, 0x74, 0x72, 0x65, 0x65, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x4d, 0x5f, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_module_number_proto_rawDescOnce sync.Once
	file_msg_module_number_proto_rawDescData = file_msg_module_number_proto_rawDesc
)

func file_msg_module_number_proto_rawDescGZIP() []byte {
	file_msg_module_number_proto_rawDescOnce.Do(func() {
		file_msg_module_number_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_module_number_proto_rawDescData)
	})
	return file_msg_module_number_proto_rawDescData
}

var file_msg_module_number_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_module_number_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_msg_module_number_proto_goTypes = []interface{}{
	(ModuleType)(0),                  // 0: msg.ModuleType
	(*ModuleNumberInfo_C)(nil),       // 1: msg.ModuleNumberInfo_C
	(*ModuleNumberInfo_S)(nil),       // 2: msg.ModuleNumberInfo_S
	(*ModuleNumberChangeInfo_S)(nil), // 3: msg.ModuleNumberChangeInfo_S
	nil,                              // 4: msg.ModuleNumberInfo_S.DayNumEntry
	nil,                              // 5: msg.ModuleNumberInfo_S.AllNumEntry
	nil,                              // 6: msg.ModuleNumberChangeInfo_S.DayNumEntry
	nil,                              // 7: msg.ModuleNumberChangeInfo_S.AllNumEntry
}
var file_msg_module_number_proto_depIdxs = []int32{
	4, // 0: msg.ModuleNumberInfo_S.dayNum:type_name -> msg.ModuleNumberInfo_S.DayNumEntry
	5, // 1: msg.ModuleNumberInfo_S.allNum:type_name -> msg.ModuleNumberInfo_S.AllNumEntry
	6, // 2: msg.ModuleNumberChangeInfo_S.dayNum:type_name -> msg.ModuleNumberChangeInfo_S.DayNumEntry
	7, // 3: msg.ModuleNumberChangeInfo_S.allNum:type_name -> msg.ModuleNumberChangeInfo_S.AllNumEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_msg_module_number_proto_init() }
func file_msg_module_number_proto_init() {
	if File_msg_module_number_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_module_number_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleNumberInfo_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_module_number_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleNumberInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_module_number_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleNumberChangeInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_module_number_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_module_number_proto_goTypes,
		DependencyIndexes: file_msg_module_number_proto_depIdxs,
		EnumInfos:         file_msg_module_number_proto_enumTypes,
		MessageInfos:      file_msg_module_number_proto_msgTypes,
	}.Build()
	File_msg_module_number_proto = out.File
	file_msg_module_number_proto_rawDesc = nil
	file_msg_module_number_proto_goTypes = nil
	file_msg_module_number_proto_depIdxs = nil
}
