// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msg/player_mail.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MailChangeOp int32

const (
	MailChangeOp_MAIL_UPDATE MailChangeOp = 0 //更新
	MailChangeOp_MAIL_ADD    MailChangeOp = 1 //增加
	MailChangeOp_MAIL_DEL    MailChangeOp = 2 //删除
)

// Enum value maps for MailChangeOp.
var (
	MailChangeOp_name = map[int32]string{
		0: "MAIL_UPDATE",
		1: "MAIL_ADD",
		2: "MAIL_DEL",
	}
	MailChangeOp_value = map[string]int32{
		"MAIL_UPDATE": 0,
		"MAIL_ADD":    1,
		"MAIL_DEL":    2,
	}
)

func (x MailChangeOp) Enum() *MailChangeOp {
	p := new(MailChangeOp)
	*p = x
	return p
}

func (x MailChangeOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MailChangeOp) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_player_mail_proto_enumTypes[0].Descriptor()
}

func (MailChangeOp) Type() protoreflect.EnumType {
	return &file_msg_player_mail_proto_enumTypes[0]
}

func (x MailChangeOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MailChangeOp.Descriptor instead.
func (MailChangeOp) EnumDescriptor() ([]byte, []int) {
	return file_msg_player_mail_proto_rawDescGZIP(), []int{0}
}

//个人邮件
type PlayerMailInfo_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageId int32 `protobuf:"varint,1,opt,name=pageId,proto3" json:"pageId,omitempty"` //页id（暂不生效）
}

func (x *PlayerMailInfo_C) Reset() {
	*x = PlayerMailInfo_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_player_mail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMailInfo_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMailInfo_C) ProtoMessage() {}

func (x *PlayerMailInfo_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_player_mail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMailInfo_C.ProtoReflect.Descriptor instead.
func (*PlayerMailInfo_C) Descriptor() ([]byte, []int) {
	return file_msg_player_mail_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerMailInfo_C) GetPageId() int32 {
	if x != nil {
		return x.PageId
	}
	return 0
}

type PlayerMailInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32            `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Pms    []*PlayerMailMsg `protobuf:"bytes,2,rep,name=pms,proto3" json:"pms,omitempty"` //个人邮件,存数组方便分页
}

func (x *PlayerMailInfo_S) Reset() {
	*x = PlayerMailInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_player_mail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMailInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMailInfo_S) ProtoMessage() {}

func (x *PlayerMailInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_player_mail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMailInfo_S.ProtoReflect.Descriptor instead.
func (*PlayerMailInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_player_mail_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerMailInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PlayerMailInfo_S) GetPms() []*PlayerMailMsg {
	if x != nil {
		return x.Pms
	}
	return nil
}

type PlayerMailChange_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32            `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Pms    []*PlayerMailMsg `protobuf:"bytes,2,rep,name=pms,proto3" json:"pms,omitempty"` //个人邮件
}

func (x *PlayerMailChange_S) Reset() {
	*x = PlayerMailChange_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_player_mail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMailChange_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMailChange_S) ProtoMessage() {}

func (x *PlayerMailChange_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_player_mail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMailChange_S.ProtoReflect.Descriptor instead.
func (*PlayerMailChange_S) Descriptor() ([]byte, []int) {
	return file_msg_player_mail_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerMailChange_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *PlayerMailChange_S) GetPms() []*PlayerMailMsg {
	if x != nil {
		return x.Pms
	}
	return nil
}

type PlayerMailMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid           int32           `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Tid           int32           `protobuf:"varint,2,opt,name=tid,proto3" json:"tid,omitempty"`
	CreateTime    int64           `protobuf:"varint,3,opt,name=createTime,proto3" json:"createTime,omitempty"`                                                                                //创建时间
	EndTime       int64           `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`                                                                                      //失效时间
	ReceiveType   int32           `protobuf:"varint,5,opt,name=receiveType,proto3" json:"receiveType,omitempty"`                                                                              //附件领取状态 0未领取 1已领取
	Items         map[int32]int32 `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //附件
	SendName      string          `protobuf:"bytes,7,opt,name=sendName,proto3" json:"sendName,omitempty"`                                                                                     //发送人姓名
	SendPlayerUid string          `protobuf:"bytes,8,opt,name=sendPlayerUid,proto3" json:"sendPlayerUid,omitempty"`                                                                           //发送人id
	Parameter     []string        `protobuf:"bytes,9,rep,name=parameter,proto3" json:"parameter,omitempty"`                                                                                   //参数
	LanguageText  string          `protobuf:"bytes,10,opt,name=languageText,proto3" json:"languageText,omitempty"`                                                                            //文本
}

func (x *PlayerMailMsg) Reset() {
	*x = PlayerMailMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_player_mail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerMailMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerMailMsg) ProtoMessage() {}

func (x *PlayerMailMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_player_mail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerMailMsg.ProtoReflect.Descriptor instead.
func (*PlayerMailMsg) Descriptor() ([]byte, []int) {
	return file_msg_player_mail_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerMailMsg) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PlayerMailMsg) GetTid() int32 {
	if x != nil {
		return x.Tid
	}
	return 0
}

func (x *PlayerMailMsg) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *PlayerMailMsg) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *PlayerMailMsg) GetReceiveType() int32 {
	if x != nil {
		return x.ReceiveType
	}
	return 0
}

func (x *PlayerMailMsg) GetItems() map[int32]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PlayerMailMsg) GetSendName() string {
	if x != nil {
		return x.SendName
	}
	return ""
}

func (x *PlayerMailMsg) GetSendPlayerUid() string {
	if x != nil {
		return x.SendPlayerUid
	}
	return ""
}

func (x *PlayerMailMsg) GetParameter() []string {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *PlayerMailMsg) GetLanguageText() string {
	if x != nil {
		return x.LanguageText
	}
	return ""
}

//领附件
type ReceiveMailItems_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	MailUid int32 `protobuf:"varint,2,opt,name=mailUid,proto3" json:"mailUid,omitempty"` //全部领取 -1
}

func (x *ReceiveMailItems_C) Reset() {
	*x = ReceiveMailItems_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_player_mail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveMailItems_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMailItems_C) ProtoMessage() {}

func (x *ReceiveMailItems_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_player_mail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMailItems_C.ProtoReflect.Descriptor instead.
func (*ReceiveMailItems_C) Descriptor() ([]byte, []int) {
	return file_msg_player_mail_proto_rawDescGZIP(), []int{4}
}

func (x *ReceiveMailItems_C) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ReceiveMailItems_C) GetMailUid() int32 {
	if x != nil {
		return x.MailUid
	}
	return 0
}

type ReceiveMailItems_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ReceiveMailItems_S) Reset() {
	*x = ReceiveMailItems_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_player_mail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveMailItems_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveMailItems_S) ProtoMessage() {}

func (x *ReceiveMailItems_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_player_mail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveMailItems_S.ProtoReflect.Descriptor instead.
func (*ReceiveMailItems_S) Descriptor() ([]byte, []int) {
	return file_msg_player_mail_proto_rawDescGZIP(), []int{5}
}

func (x *ReceiveMailItems_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_msg_player_mail_proto protoreflect.FileDescriptor

var file_msg_player_mail_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6d, 0x73, 0x67, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6d, 0x61, 0x69,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x2a, 0x0a, 0x10,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x43,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x70, 0x61, 0x67, 0x65, 0x49, 0x64, 0x22, 0x50, 0x0a, 0x10, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x03, 0x70, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x61,
	0x69, 0x6c, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x70, 0x6d, 0x73, 0x22, 0x52, 0x0a, 0x12, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x24, 0x0a, 0x03, 0x70, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x4d, 0x73, 0x67, 0x52, 0x03, 0x70, 0x6d, 0x73, 0x22, 0x82,
	0x03, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x4d, 0x73, 0x67,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x74, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x33, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x61, 0x69, 0x6c,
	0x4d, 0x73, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x55,
	0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x64, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x55, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x54, 0x65, 0x78, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x54, 0x65, 0x78, 0x74, 0x1a, 0x38, 0x0a, 0x0a, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x46, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x61,
	0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x43, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x69, 0x6c, 0x55, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x4d, 0x61, 0x69, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x5f,
	0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x3b, 0x0a, 0x0c, 0x4d, 0x61, 0x69,
	0x6c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x70, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x41, 0x49,
	0x4c, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x41,
	0x49, 0x4c, 0x5f, 0x41, 0x44, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x41, 0x49, 0x4c,
	0x5f, 0x44, 0x45, 0x4c, 0x10, 0x02, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_player_mail_proto_rawDescOnce sync.Once
	file_msg_player_mail_proto_rawDescData = file_msg_player_mail_proto_rawDesc
)

func file_msg_player_mail_proto_rawDescGZIP() []byte {
	file_msg_player_mail_proto_rawDescOnce.Do(func() {
		file_msg_player_mail_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_player_mail_proto_rawDescData)
	})
	return file_msg_player_mail_proto_rawDescData
}

var file_msg_player_mail_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_player_mail_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_msg_player_mail_proto_goTypes = []interface{}{
	(MailChangeOp)(0),          // 0: msg.MailChangeOp
	(*PlayerMailInfo_C)(nil),   // 1: msg.PlayerMailInfo_C
	(*PlayerMailInfo_S)(nil),   // 2: msg.PlayerMailInfo_S
	(*PlayerMailChange_S)(nil), // 3: msg.PlayerMailChange_S
	(*PlayerMailMsg)(nil),      // 4: msg.PlayerMailMsg
	(*ReceiveMailItems_C)(nil), // 5: msg.ReceiveMailItems_C
	(*ReceiveMailItems_S)(nil), // 6: msg.ReceiveMailItems_S
	nil,                        // 7: msg.PlayerMailMsg.ItemsEntry
}
var file_msg_player_mail_proto_depIdxs = []int32{
	4, // 0: msg.PlayerMailInfo_S.pms:type_name -> msg.PlayerMailMsg
	4, // 1: msg.PlayerMailChange_S.pms:type_name -> msg.PlayerMailMsg
	7, // 2: msg.PlayerMailMsg.items:type_name -> msg.PlayerMailMsg.ItemsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_msg_player_mail_proto_init() }
func file_msg_player_mail_proto_init() {
	if File_msg_player_mail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_player_mail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMailInfo_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_player_mail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMailInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_player_mail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMailChange_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_player_mail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerMailMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_player_mail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveMailItems_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_player_mail_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveMailItems_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_player_mail_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_player_mail_proto_goTypes,
		DependencyIndexes: file_msg_player_mail_proto_depIdxs,
		EnumInfos:         file_msg_player_mail_proto_enumTypes,
		MessageInfos:      file_msg_player_mail_proto_msgTypes,
	}.Build()
	File_msg_player_mail_proto = out.File
	file_msg_player_mail_proto_rawDesc = nil
	file_msg_player_mail_proto_goTypes = nil
	file_msg_player_mail_proto_depIdxs = nil
}
