// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: msg/special_building.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//许愿树信息
type WishTreeInfo_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WishTreeInfo_C) Reset() {
	*x = WishTreeInfo_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishTreeInfo_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishTreeInfo_C) ProtoMessage() {}

func (x *WishTreeInfo_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishTreeInfo_C.ProtoReflect.Descriptor instead.
func (*WishTreeInfo_C) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{0}
}

type WishTreeInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32        `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	WmInfo *WishTreeMsg `protobuf:"bytes,2,opt,name=wmInfo,proto3" json:"wmInfo,omitempty"`
}

func (x *WishTreeInfo_S) Reset() {
	*x = WishTreeInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishTreeInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishTreeInfo_S) ProtoMessage() {}

func (x *WishTreeInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishTreeInfo_S.ProtoReflect.Descriptor instead.
func (*WishTreeInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{1}
}

func (x *WishTreeInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *WishTreeInfo_S) GetWmInfo() *WishTreeMsg {
	if x != nil {
		return x.WmInfo
	}
	return nil
}

//许愿树信息
type WishTreeMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Orders   []*OrderMsg `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Integral int32       `protobuf:"varint,2,opt,name=integral,proto3" json:"integral,omitempty"`    //当日积分
	BoxIds   []int32     `protobuf:"varint,3,rep,packed,name=boxIds,proto3" json:"boxIds,omitempty"` //当日已经领取的宝箱id
}

func (x *WishTreeMsg) Reset() {
	*x = WishTreeMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishTreeMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishTreeMsg) ProtoMessage() {}

func (x *WishTreeMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishTreeMsg.ProtoReflect.Descriptor instead.
func (*WishTreeMsg) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{2}
}

func (x *WishTreeMsg) GetOrders() []*OrderMsg {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *WishTreeMsg) GetIntegral() int32 {
	if x != nil {
		return x.Integral
	}
	return 0
}

func (x *WishTreeMsg) GetBoxIds() []int32 {
	if x != nil {
		return x.BoxIds
	}
	return nil
}

//愿望单
type OrderMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` //位置
	// Deprecated: Do not use.
	EndTime  int64           `protobuf:"varint,2,opt,name=endTime,proto3" json:"endTime,omitempty"`                                                                                      //cd结束时间（------------------作废）
	Items    map[int32]int32 `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"` //订单详情
	OpenType int32           `protobuf:"varint,4,opt,name=openType,proto3" json:"openType,omitempty"`                                                                                    //订单状态 0默认， 1展开
	Cd       *CDInfo         `protobuf:"bytes,5,opt,name=cd,proto3" json:"cd,omitempty"`                                                                                                 //新cd
}

func (x *OrderMsg) Reset() {
	*x = OrderMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMsg) ProtoMessage() {}

func (x *OrderMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMsg.ProtoReflect.Descriptor instead.
func (*OrderMsg) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{3}
}

func (x *OrderMsg) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// Deprecated: Do not use.
func (x *OrderMsg) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *OrderMsg) GetItems() map[int32]int32 {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderMsg) GetOpenType() int32 {
	if x != nil {
		return x.OpenType
	}
	return 0
}

func (x *OrderMsg) GetCd() *CDInfo {
	if x != nil {
		return x.Cd
	}
	return nil
}

//提交订单
type WishTreeSubmit_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` //位置
}

func (x *WishTreeSubmit_C) Reset() {
	*x = WishTreeSubmit_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishTreeSubmit_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishTreeSubmit_C) ProtoMessage() {}

func (x *WishTreeSubmit_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishTreeSubmit_C.ProtoReflect.Descriptor instead.
func (*WishTreeSubmit_C) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{4}
}

func (x *WishTreeSubmit_C) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type WishTreeSubmit_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result   int32     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Order    *OrderMsg `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`        //刷新后的订单
	Integral int32     `protobuf:"varint,3,opt,name=integral,proto3" json:"integral,omitempty"` //当日积分
}

func (x *WishTreeSubmit_S) Reset() {
	*x = WishTreeSubmit_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishTreeSubmit_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishTreeSubmit_S) ProtoMessage() {}

func (x *WishTreeSubmit_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishTreeSubmit_S.ProtoReflect.Descriptor instead.
func (*WishTreeSubmit_S) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{5}
}

func (x *WishTreeSubmit_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *WishTreeSubmit_S) GetOrder() *OrderMsg {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *WishTreeSubmit_S) GetIntegral() int32 {
	if x != nil {
		return x.Integral
	}
	return 0
}

//领取积分宝箱, 成功后客户端追加id
type WishTreeOpenBox_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BoxId int32 `protobuf:"varint,1,opt,name=boxId,proto3" json:"boxId,omitempty"` //位置
}

func (x *WishTreeOpenBox_C) Reset() {
	*x = WishTreeOpenBox_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishTreeOpenBox_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishTreeOpenBox_C) ProtoMessage() {}

func (x *WishTreeOpenBox_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishTreeOpenBox_C.ProtoReflect.Descriptor instead.
func (*WishTreeOpenBox_C) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{6}
}

func (x *WishTreeOpenBox_C) GetBoxId() int32 {
	if x != nil {
		return x.BoxId
	}
	return 0
}

type WishTreeOpenBox_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *WishTreeOpenBox_S) Reset() {
	*x = WishTreeOpenBox_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishTreeOpenBox_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishTreeOpenBox_S) ProtoMessage() {}

func (x *WishTreeOpenBox_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishTreeOpenBox_S.ProtoReflect.Descriptor instead.
func (*WishTreeOpenBox_S) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{7}
}

func (x *WishTreeOpenBox_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

//展开订单
type WishTreeOpen_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` //位置
}

func (x *WishTreeOpen_C) Reset() {
	*x = WishTreeOpen_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishTreeOpen_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishTreeOpen_C) ProtoMessage() {}

func (x *WishTreeOpen_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishTreeOpen_C.ProtoReflect.Descriptor instead.
func (*WishTreeOpen_C) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{8}
}

func (x *WishTreeOpen_C) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type WishTreeOpen_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Index  int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` //位置
}

func (x *WishTreeOpen_S) Reset() {
	*x = WishTreeOpen_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WishTreeOpen_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WishTreeOpen_S) ProtoMessage() {}

func (x *WishTreeOpen_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WishTreeOpen_S.ProtoReflect.Descriptor instead.
func (*WishTreeOpen_S) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{9}
}

func (x *WishTreeOpen_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *WishTreeOpen_S) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

//刷新订单
type RefreshOrderItem_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` //位置
}

func (x *RefreshOrderItem_C) Reset() {
	*x = RefreshOrderItem_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshOrderItem_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshOrderItem_C) ProtoMessage() {}

func (x *RefreshOrderItem_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshOrderItem_C.ProtoReflect.Descriptor instead.
func (*RefreshOrderItem_C) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshOrderItem_C) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type RefreshOrderItem_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Order  *OrderMsg `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"` //刷新后的订单
}

func (x *RefreshOrderItem_S) Reset() {
	*x = RefreshOrderItem_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RefreshOrderItem_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshOrderItem_S) ProtoMessage() {}

func (x *RefreshOrderItem_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshOrderItem_S.ProtoReflect.Descriptor instead.
func (*RefreshOrderItem_S) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshOrderItem_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *RefreshOrderItem_S) GetOrder() *OrderMsg {
	if x != nil {
		return x.Order
	}
	return nil
}

//获得火车信息
type TrainInfo_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrainInfo_C) Reset() {
	*x = TrainInfo_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainInfo_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainInfo_C) ProtoMessage() {}

func (x *TrainInfo_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainInfo_C.ProtoReflect.Descriptor instead.
func (*TrainInfo_C) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{12}
}

type TrainInfo_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Train  *TrainMsg `protobuf:"bytes,2,opt,name=train,proto3" json:"train,omitempty"`
}

func (x *TrainInfo_S) Reset() {
	*x = TrainInfo_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainInfo_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainInfo_S) ProtoMessage() {}

func (x *TrainInfo_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainInfo_S.ProtoReflect.Descriptor instead.
func (*TrainInfo_S) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{13}
}

func (x *TrainInfo_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TrainInfo_S) GetTrain() *TrainMsg {
	if x != nil {
		return x.Train
	}
	return nil
}

//小火车信息
type TrainMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ts []*TrackMsg `protobuf:"bytes,1,rep,name=ts,proto3" json:"ts,omitempty"` //轨道信息
}

func (x *TrainMsg) Reset() {
	*x = TrainMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrainMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainMsg) ProtoMessage() {}

func (x *TrainMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainMsg.ProtoReflect.Descriptor instead.
func (*TrainMsg) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{14}
}

func (x *TrainMsg) GetTs() []*TrackMsg {
	if x != nil {
		return x.Ts
	}
	return nil
}

//单条轨道
type TrackMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId int32     `protobuf:"varint,1,opt,name=trackId,proto3" json:"trackId,omitempty"` //轨道id
	Cs      []*CarMsg `protobuf:"bytes,2,rep,name=cs,proto3" json:"cs,omitempty"`            //车厢
	// Deprecated: Do not use.
	EndTime int64   `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime,omitempty"` //结束时间戳（-----------------------------作废）
	Cd      *CDInfo `protobuf:"bytes,4,opt,name=cd,proto3" json:"cd,omitempty"`            //新cd
}

func (x *TrackMsg) Reset() {
	*x = TrackMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackMsg) ProtoMessage() {}

func (x *TrackMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackMsg.ProtoReflect.Descriptor instead.
func (*TrackMsg) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{15}
}

func (x *TrackMsg) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *TrackMsg) GetCs() []*CarMsg {
	if x != nil {
		return x.Cs
	}
	return nil
}

// Deprecated: Do not use.
func (x *TrackMsg) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *TrackMsg) GetCd() *CDInfo {
	if x != nil {
		return x.Cd
	}
	return nil
}

//车厢
type CarMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index         int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                 //位置
	TrainItemId   int32 `protobuf:"varint,2,opt,name=trainItemId,proto3" json:"trainItemId,omitempty"`     //需要的物品id
	TrainItemNum  int32 `protobuf:"varint,3,opt,name=trainItemNum,proto3" json:"trainItemNum,omitempty"`   //需要的物品数量
	RewardItemId  int32 `protobuf:"varint,4,opt,name=rewardItemId,proto3" json:"rewardItemId,omitempty"`   //需要的物品id
	RewardItemNum int32 `protobuf:"varint,5,opt,name=rewardItemNum,proto3" json:"rewardItemNum,omitempty"` //需要的物品数量
	CarType       int32 `protobuf:"varint,6,opt,name=carType,proto3" json:"carType,omitempty"`             //提交状态 0未提交 1提交
}

func (x *CarMsg) Reset() {
	*x = CarMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarMsg) ProtoMessage() {}

func (x *CarMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarMsg.ProtoReflect.Descriptor instead.
func (*CarMsg) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{16}
}

func (x *CarMsg) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *CarMsg) GetTrainItemId() int32 {
	if x != nil {
		return x.TrainItemId
	}
	return 0
}

func (x *CarMsg) GetTrainItemNum() int32 {
	if x != nil {
		return x.TrainItemNum
	}
	return 0
}

func (x *CarMsg) GetRewardItemId() int32 {
	if x != nil {
		return x.RewardItemId
	}
	return 0
}

func (x *CarMsg) GetRewardItemNum() int32 {
	if x != nil {
		return x.RewardItemNum
	}
	return 0
}

func (x *CarMsg) GetCarType() int32 {
	if x != nil {
		return x.CarType
	}
	return 0
}

//解锁轨道
type UnlockTrack_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId int32 `protobuf:"varint,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
}

func (x *UnlockTrack_C) Reset() {
	*x = UnlockTrack_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockTrack_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockTrack_C) ProtoMessage() {}

func (x *UnlockTrack_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockTrack_C.ProtoReflect.Descriptor instead.
func (*UnlockTrack_C) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{17}
}

func (x *UnlockTrack_C) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

type UnlockTrack_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Ts     *TrackMsg `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *UnlockTrack_S) Reset() {
	*x = UnlockTrack_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnlockTrack_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockTrack_S) ProtoMessage() {}

func (x *UnlockTrack_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockTrack_S.ProtoReflect.Descriptor instead.
func (*UnlockTrack_S) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{18}
}

func (x *UnlockTrack_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *UnlockTrack_S) GetTs() *TrackMsg {
	if x != nil {
		return x.Ts
	}
	return nil
}

//道具交付
type CommitTrack_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId int32 `protobuf:"varint,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
	Index   int32 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` //可选项
}

func (x *CommitTrack_C) Reset() {
	*x = CommitTrack_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitTrack_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTrack_C) ProtoMessage() {}

func (x *CommitTrack_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTrack_C.ProtoReflect.Descriptor instead.
func (*CommitTrack_C) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{19}
}

func (x *CommitTrack_C) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

func (x *CommitTrack_C) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type CommitTrack_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Ts     *TrackMsg `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *CommitTrack_S) Reset() {
	*x = CommitTrack_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitTrack_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTrack_S) ProtoMessage() {}

func (x *CommitTrack_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTrack_S.ProtoReflect.Descriptor instead.
func (*CommitTrack_S) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{20}
}

func (x *CommitTrack_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *CommitTrack_S) GetTs() *TrackMsg {
	if x != nil {
		return x.Ts
	}
	return nil
}

//领奖
type TrackReward_C struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrackId int32 `protobuf:"varint,1,opt,name=trackId,proto3" json:"trackId,omitempty"`
}

func (x *TrackReward_C) Reset() {
	*x = TrackReward_C{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackReward_C) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackReward_C) ProtoMessage() {}

func (x *TrackReward_C) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackReward_C.ProtoReflect.Descriptor instead.
func (*TrackReward_C) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{21}
}

func (x *TrackReward_C) GetTrackId() int32 {
	if x != nil {
		return x.TrackId
	}
	return 0
}

type TrackReward_S struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Ts     *TrackMsg `protobuf:"bytes,2,opt,name=ts,proto3" json:"ts,omitempty"`
}

func (x *TrackReward_S) Reset() {
	*x = TrackReward_S{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_special_building_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackReward_S) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackReward_S) ProtoMessage() {}

func (x *TrackReward_S) ProtoReflect() protoreflect.Message {
	mi := &file_msg_special_building_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackReward_S.ProtoReflect.Descriptor instead.
func (*TrackReward_S) Descriptor() ([]byte, []int) {
	return file_msg_special_building_proto_rawDescGZIP(), []int{22}
}

func (x *TrackReward_S) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TrackReward_S) GetTs() *TrackMsg {
	if x != nil {
		return x.Ts
	}
	return nil
}

var File_msg_special_building_proto protoreflect.FileDescriptor

var file_msg_special_building_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x73, 0x67, 0x2f, 0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x62, 0x75,
	0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x73,
	0x67, 0x1a, 0x10, 0x6d, 0x73, 0x67, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x57, 0x69, 0x73, 0x68, 0x54, 0x72, 0x65, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x5f, 0x43, 0x22, 0x52, 0x0a, 0x0e, 0x57, 0x69, 0x73, 0x68, 0x54, 0x72, 0x65,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x28, 0x0a, 0x06, 0x77, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x57, 0x69, 0x73, 0x68, 0x54, 0x72, 0x65, 0x65, 0x4d, 0x73,
	0x67, 0x52, 0x06, 0x77, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x68, 0x0a, 0x0b, 0x57, 0x69, 0x73,
	0x68, 0x54, 0x72, 0x65, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x06, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x06, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x62,
	0x6f, 0x78, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06, 0x62, 0x6f, 0x78,
	0x49, 0x64, 0x73, 0x22, 0xe1, 0x01, 0x0a, 0x08, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x73, 0x67,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1c, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x18, 0x01, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d,
	0x73, 0x67, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1b, 0x0a, 0x02, 0x63, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x43, 0x44, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02, 0x63, 0x64, 0x1a, 0x38, 0x0a,
	0x0a, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x28, 0x0a, 0x10, 0x57, 0x69, 0x73, 0x68, 0x54,
	0x72, 0x65, 0x65, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x22, 0x6b, 0x0a, 0x10, 0x57, 0x69, 0x73, 0x68, 0x54, 0x72, 0x65, 0x65, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x23, 0x0a,
	0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x6c, 0x22, 0x29,
	0x0a, 0x11, 0x57, 0x69, 0x73, 0x68, 0x54, 0x72, 0x65, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x42, 0x6f,
	0x78, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x62, 0x6f, 0x78, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x11, 0x57, 0x69, 0x73,
	0x68, 0x54, 0x72, 0x65, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x42, 0x6f, 0x78, 0x5f, 0x53, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x26, 0x0a, 0x0e, 0x57, 0x69, 0x73, 0x68, 0x54, 0x72,
	0x65, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x3e,
	0x0a, 0x0e, 0x57, 0x69, 0x73, 0x68, 0x54, 0x72, 0x65, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x5f, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x2a,
	0x0a, 0x12, 0x52, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74,
	0x65, 0x6d, 0x5f, 0x43, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x51, 0x0a, 0x12, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x5f, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x4d, 0x73, 0x67, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x0d, 0x0a,
	0x0b, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x43, 0x22, 0x4a, 0x0a, 0x0b,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x4d, 0x73,
	0x67, 0x52, 0x05, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x22, 0x29, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x4d, 0x73, 0x67, 0x12, 0x1d, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x52,
	0x02, 0x74, 0x73, 0x22, 0x7c, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x02, 0x63, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x61, 0x72, 0x4d,
	0x73, 0x67, 0x52, 0x02, 0x63, 0x73, 0x12, 0x1c, 0x0a, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x42, 0x02, 0x18, 0x01, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x02, 0x63, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x43, 0x44, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x02, 0x63,
	0x64, 0x22, 0xc8, 0x01, 0x0a, 0x06, 0x43, 0x61, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x74, 0x65, 0x6d, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x74,
	0x65, 0x6d, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x74, 0x65,
	0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d,
	0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0d, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x4e,
	0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x29, 0x0a, 0x0d,
	0x55, 0x6e, 0x6c, 0x6f, 0x63, 0x6b, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x43, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x0d, 0x55, 0x6e, 0x6c, 0x6f, 0x63,
	0x6b, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x1d, 0x0a, 0x02, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d,
	0x73, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x52, 0x02, 0x74, 0x73, 0x22,
	0x3f, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x5f, 0x43,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x22, 0x46, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x5f,
	0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x02, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x4d, 0x73, 0x67, 0x52, 0x02, 0x74, 0x73, 0x22, 0x29, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x43, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x77, 0x61,
	0x72, 0x64, 0x5f, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x2e, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x4d, 0x73, 0x67, 0x52, 0x02, 0x74, 0x73, 0x42, 0x0a, 0x5a, 0x08, 0x2f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_special_building_proto_rawDescOnce sync.Once
	file_msg_special_building_proto_rawDescData = file_msg_special_building_proto_rawDesc
)

func file_msg_special_building_proto_rawDescGZIP() []byte {
	file_msg_special_building_proto_rawDescOnce.Do(func() {
		file_msg_special_building_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_special_building_proto_rawDescData)
	})
	return file_msg_special_building_proto_rawDescData
}

var file_msg_special_building_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_msg_special_building_proto_goTypes = []interface{}{
	(*WishTreeInfo_C)(nil),     // 0: msg.WishTreeInfo_C
	(*WishTreeInfo_S)(nil),     // 1: msg.WishTreeInfo_S
	(*WishTreeMsg)(nil),        // 2: msg.WishTreeMsg
	(*OrderMsg)(nil),           // 3: msg.OrderMsg
	(*WishTreeSubmit_C)(nil),   // 4: msg.WishTreeSubmit_C
	(*WishTreeSubmit_S)(nil),   // 5: msg.WishTreeSubmit_S
	(*WishTreeOpenBox_C)(nil),  // 6: msg.WishTreeOpenBox_C
	(*WishTreeOpenBox_S)(nil),  // 7: msg.WishTreeOpenBox_S
	(*WishTreeOpen_C)(nil),     // 8: msg.WishTreeOpen_C
	(*WishTreeOpen_S)(nil),     // 9: msg.WishTreeOpen_S
	(*RefreshOrderItem_C)(nil), // 10: msg.RefreshOrderItem_C
	(*RefreshOrderItem_S)(nil), // 11: msg.RefreshOrderItem_S
	(*TrainInfo_C)(nil),        // 12: msg.TrainInfo_C
	(*TrainInfo_S)(nil),        // 13: msg.TrainInfo_S
	(*TrainMsg)(nil),           // 14: msg.TrainMsg
	(*TrackMsg)(nil),           // 15: msg.TrackMsg
	(*CarMsg)(nil),             // 16: msg.CarMsg
	(*UnlockTrack_C)(nil),      // 17: msg.UnlockTrack_C
	(*UnlockTrack_S)(nil),      // 18: msg.UnlockTrack_S
	(*CommitTrack_C)(nil),      // 19: msg.CommitTrack_C
	(*CommitTrack_S)(nil),      // 20: msg.CommitTrack_S
	(*TrackReward_C)(nil),      // 21: msg.TrackReward_C
	(*TrackReward_S)(nil),      // 22: msg.TrackReward_S
	nil,                        // 23: msg.OrderMsg.ItemsEntry
	(*CDInfo)(nil),             // 24: msg.CDInfo
}
var file_msg_special_building_proto_depIdxs = []int32{
	2,  // 0: msg.WishTreeInfo_S.wmInfo:type_name -> msg.WishTreeMsg
	3,  // 1: msg.WishTreeMsg.orders:type_name -> msg.OrderMsg
	23, // 2: msg.OrderMsg.items:type_name -> msg.OrderMsg.ItemsEntry
	24, // 3: msg.OrderMsg.cd:type_name -> msg.CDInfo
	3,  // 4: msg.WishTreeSubmit_S.order:type_name -> msg.OrderMsg
	3,  // 5: msg.RefreshOrderItem_S.order:type_name -> msg.OrderMsg
	14, // 6: msg.TrainInfo_S.train:type_name -> msg.TrainMsg
	15, // 7: msg.TrainMsg.ts:type_name -> msg.TrackMsg
	16, // 8: msg.TrackMsg.cs:type_name -> msg.CarMsg
	24, // 9: msg.TrackMsg.cd:type_name -> msg.CDInfo
	15, // 10: msg.UnlockTrack_S.ts:type_name -> msg.TrackMsg
	15, // 11: msg.CommitTrack_S.ts:type_name -> msg.TrackMsg
	15, // 12: msg.TrackReward_S.ts:type_name -> msg.TrackMsg
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_msg_special_building_proto_init() }
func file_msg_special_building_proto_init() {
	if File_msg_special_building_proto != nil {
		return
	}
	file_msg_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_msg_special_building_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishTreeInfo_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishTreeInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishTreeMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishTreeSubmit_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishTreeSubmit_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishTreeOpenBox_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishTreeOpenBox_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishTreeOpen_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WishTreeOpen_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshOrderItem_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RefreshOrderItem_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainInfo_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainInfo_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrainMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockTrack_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnlockTrack_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitTrack_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitTrack_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackReward_C); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_special_building_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrackReward_S); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_special_building_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_special_building_proto_goTypes,
		DependencyIndexes: file_msg_special_building_proto_depIdxs,
		MessageInfos:      file_msg_special_building_proto_msgTypes,
	}.Build()
	File_msg_special_building_proto = out.File
	file_msg_special_building_proto_rawDesc = nil
	file_msg_special_building_proto_goTypes = nil
	file_msg_special_building_proto_depIdxs = nil
}
